%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_
options_ = [];
M_.fname = 'mediumdsge';
%
% Some global variables initialization
%
global_initialization;
diary off;
logname_ = 'mediumdsge.log';
if exist(logname_, 'file')
    delete(logname_)
end
diary(logname_)
M_.exo_names = 'eg';
M_.exo_names_tex = 'eg';
M_.exo_names = char(M_.exo_names, 'ei');
M_.exo_names_tex = char(M_.exo_names_tex, 'ei');
M_.exo_names = char(M_.exo_names, 'ea');
M_.exo_names_tex = char(M_.exo_names_tex, 'ea');
M_.exo_names = char(M_.exo_names, 'ez');
M_.exo_names_tex = char(M_.exo_names_tex, 'ez');
M_.endo_names = 'lam';
M_.endo_names_tex = 'lam';
M_.endo_names = char(M_.endo_names, 'C');
M_.endo_names_tex = char(M_.endo_names_tex, 'C');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names = char(M_.endo_names, 'mu');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu');
M_.endo_names = char(M_.endo_names, 'inv');
M_.endo_names_tex = char(M_.endo_names_tex, 'inv');
M_.endo_names = char(M_.endo_names, 'wstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'wstar');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names = char(M_.endo_names, 'x1');
M_.endo_names_tex = char(M_.endo_names_tex, 'x1');
M_.endo_names = char(M_.endo_names, 'x2');
M_.endo_names_tex = char(M_.endo_names_tex, 'x2');
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y');
M_.endo_names = char(M_.endo_names, 'A');
M_.endo_names_tex = char(M_.endo_names_tex, 'A');
M_.endo_names = char(M_.endo_names, 'N');
M_.endo_names_tex = char(M_.endo_names_tex, 'N');
M_.endo_names = char(M_.endo_names, 'vp');
M_.endo_names_tex = char(M_.endo_names_tex, 'vp');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names = char(M_.endo_names, 'pistar');
M_.endo_names_tex = char(M_.endo_names_tex, 'pistar');
M_.endo_names = char(M_.endo_names, 'h1');
M_.endo_names_tex = char(M_.endo_names_tex, 'h1');
M_.endo_names = char(M_.endo_names, 'h2');
M_.endo_names_tex = char(M_.endo_names_tex, 'h2');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, 'K');
M_.endo_names = char(M_.endo_names, 'Kbar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kbar');
M_.endo_names = char(M_.endo_names, 'G');
M_.endo_names_tex = char(M_.endo_names_tex, 'G');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names = char(M_.endo_names, 'omegag');
M_.endo_names_tex = char(M_.endo_names_tex, 'omegag');
M_.param_names = 'beta';
M_.param_names_tex = 'beta';
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names = char(M_.param_names, 'b');
M_.param_names_tex = char(M_.param_names_tex, 'b');
M_.param_names = char(M_.param_names, 'tau');
M_.param_names_tex = char(M_.param_names_tex, 'tau');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names = char(M_.param_names, 'omegags');
M_.param_names_tex = char(M_.param_names_tex, 'omegags');
M_.param_names = char(M_.param_names, 'psi');
M_.param_names_tex = char(M_.param_names_tex, 'psi');
M_.param_names = char(M_.param_names, 'epsw');
M_.param_names_tex = char(M_.param_names_tex, 'epsw');
M_.param_names = char(M_.param_names, 'epsp');
M_.param_names_tex = char(M_.param_names_tex, 'epsp');
M_.param_names = char(M_.param_names, 'phiw');
M_.param_names_tex = char(M_.param_names_tex, 'phiw');
M_.param_names = char(M_.param_names, 'phip');
M_.param_names_tex = char(M_.param_names_tex, 'phip');
M_.param_names = char(M_.param_names, 'chi1');
M_.param_names_tex = char(M_.param_names_tex, 'chi1');
M_.param_names = char(M_.param_names, 'chi2');
M_.param_names_tex = char(M_.param_names_tex, 'chi2');
M_.param_names = char(M_.param_names, 'rhog');
M_.param_names_tex = char(M_.param_names_tex, 'rhog');
M_.param_names = char(M_.param_names, 'rhoi');
M_.param_names_tex = char(M_.param_names_tex, 'rhoi');
M_.param_names = char(M_.param_names, 'rhoa');
M_.param_names_tex = char(M_.param_names_tex, 'rhoa');
M_.param_names = char(M_.param_names, 'rhoz');
M_.param_names_tex = char(M_.param_names_tex, 'rhoz');
M_.param_names = char(M_.param_names, 'sdg');
M_.param_names_tex = char(M_.param_names_tex, 'sdg');
M_.param_names = char(M_.param_names, 'sdi');
M_.param_names_tex = char(M_.param_names_tex, 'sdi');
M_.param_names = char(M_.param_names, 'sda');
M_.param_names_tex = char(M_.param_names_tex, 'sda');
M_.param_names = char(M_.param_names, 'sdz');
M_.param_names_tex = char(M_.param_names_tex, 'sdz');
M_.param_names = char(M_.param_names, 'phipi');
M_.param_names_tex = char(M_.param_names_tex, 'phipi');
M_.param_names = char(M_.param_names, 'phiy');
M_.param_names_tex = char(M_.param_names_tex, 'phiy');
M_.param_names = char(M_.param_names, 'lams');
M_.param_names_tex = char(M_.param_names_tex, 'lams');
M_.param_names = char(M_.param_names, 'Cs');
M_.param_names_tex = char(M_.param_names_tex, 'Cs');
M_.param_names = char(M_.param_names, 'Rs');
M_.param_names_tex = char(M_.param_names_tex, 'Rs');
M_.param_names = char(M_.param_names, 'zs');
M_.param_names_tex = char(M_.param_names_tex, 'zs');
M_.param_names = char(M_.param_names, 'is');
M_.param_names_tex = char(M_.param_names_tex, 'is');
M_.param_names = char(M_.param_names, 'us');
M_.param_names_tex = char(M_.param_names_tex, 'us');
M_.param_names = char(M_.param_names, 'mus');
M_.param_names_tex = char(M_.param_names_tex, 'mus');
M_.param_names = char(M_.param_names, 'invs');
M_.param_names_tex = char(M_.param_names_tex, 'invs');
M_.param_names = char(M_.param_names, 'wstars');
M_.param_names_tex = char(M_.param_names_tex, 'wstars');
M_.param_names = char(M_.param_names, 'ws');
M_.param_names_tex = char(M_.param_names_tex, 'ws');
M_.param_names = char(M_.param_names, 'x1s');
M_.param_names_tex = char(M_.param_names_tex, 'x1s');
M_.param_names = char(M_.param_names, 'x2s');
M_.param_names_tex = char(M_.param_names_tex, 'x2s');
M_.param_names = char(M_.param_names, 'Ys');
M_.param_names_tex = char(M_.param_names_tex, 'Ys');
M_.param_names = char(M_.param_names, 'As');
M_.param_names_tex = char(M_.param_names_tex, 'As');
M_.param_names = char(M_.param_names, 'Ns');
M_.param_names_tex = char(M_.param_names_tex, 'Ns');
M_.param_names = char(M_.param_names, 'vps');
M_.param_names_tex = char(M_.param_names_tex, 'vps');
M_.param_names = char(M_.param_names, 'pis');
M_.param_names_tex = char(M_.param_names_tex, 'pis');
M_.param_names = char(M_.param_names, 'pistars');
M_.param_names_tex = char(M_.param_names_tex, 'pistars');
M_.param_names = char(M_.param_names, 'h1s');
M_.param_names_tex = char(M_.param_names_tex, 'h1s');
M_.param_names = char(M_.param_names, 'h2s');
M_.param_names_tex = char(M_.param_names_tex, 'h2s');
M_.param_names = char(M_.param_names, 'mcs');
M_.param_names_tex = char(M_.param_names_tex, 'mcs');
M_.param_names = char(M_.param_names, 'Ks');
M_.param_names_tex = char(M_.param_names_tex, 'Ks');
M_.param_names = char(M_.param_names, 'Kbars');
M_.param_names_tex = char(M_.param_names_tex, 'Kbars');
M_.param_names = char(M_.param_names, 'Gs');
M_.param_names_tex = char(M_.param_names_tex, 'Gs');
M_.param_names = char(M_.param_names, 'qs');
M_.param_names_tex = char(M_.param_names_tex, 'qs');
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 26;
M_.param_nbr = 49;
M_.orig_endo_nbr = 26;
M_.aux_vars = [];
M_.Sigma_e = zeros(4, 4);
M_.H = 0;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('mediumdsge_dynamic');
M_.lead_lag_incidence = [
 0 10 36;
 1 11 37;
 0 12 38;
 2 13 39;
 3 14 0;
 0 15 40;
 0 16 41;
 4 17 42;
 0 18 43;
 5 19 0;
 0 20 44;
 0 21 45;
 0 22 0;
 6 23 0;
 0 24 0;
 7 25 0;
 0 26 46;
 0 27 0;
 0 28 47;
 0 29 48;
 0 30 0;
 8 31 0;
 0 32 0;
 0 33 0;
 0 34 0;
 9 35 0;]';
M_.equations_tags = {
};
M_.exo_names_orig_ord = [1:4];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(26, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = repmat(NaN,49, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 117;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
load mediumdsge
set_param_value('beta',beta);
set_param_value('alpha',alpha);
set_param_value('delta',delta);
set_param_value('b',b);
set_param_value('tau',tau);
set_param_value('eta',eta);
set_param_value('omegags',omegags);
set_param_value('psi',psi);
set_param_value('epsw',epsw);
set_param_value('epsp',epsp);
set_param_value('phip',phip);
set_param_value('phiw',phiw);
set_param_value('chi1',chi1);
set_param_value('chi2',chi2);
set_param_value('rhog',rhog);
set_param_value('rhoa',rhoa);
set_param_value('rhoz',rhoz);
set_param_value('rhoi',rhoi);
set_param_value('sdg',sdg);
set_param_value('sda',sda);
set_param_value('sdz',sdz);
set_param_value('sdi',sdi);
set_param_value('phipi',phipi);
set_param_value('phiy',phiy);
set_param_value('lams',lams);
set_param_value('Cs',Cs);
set_param_value('Rs',Rs);
set_param_value('zs',zs);
set_param_value('is',is);
set_param_value('us',us);
set_param_value('mus',mus);
set_param_value('invs',invs);
set_param_value('wstars',wstars);
set_param_value('ws',ws);
set_param_value('x1s',x1s);
set_param_value('x2s',x2s);
set_param_value('Ys',Ys);
set_param_value('As',As);
set_param_value('Ns',Ns);
set_param_value('vps',vps);
set_param_value('pis',pis);
set_param_value('pistars',pistars);
set_param_value('h1s',h1s);
set_param_value('h2s',h2s);
set_param_value('mcs',mcs);
set_param_value('Ks',Ks);
set_param_value('Kbars',Kbars);
set_param_value('Gs',Gs);
set_param_value('qs',qs);
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 1 ) = log(M_.params(25));
oo_.steady_state( 2 ) = log(M_.params(26));
oo_.steady_state( 3 ) = M_.params(27);
oo_.steady_state( 4 ) = log(M_.params(28));
oo_.steady_state( 5 ) = log(M_.params(29));
oo_.steady_state( 6 ) = log(M_.params(30));
oo_.steady_state( 7 ) = log(M_.params(31));
oo_.steady_state( 8 ) = log(M_.params(32));
oo_.steady_state( 9 ) = log(M_.params(33));
oo_.steady_state( 10 ) = log(M_.params(34));
oo_.steady_state( 11 ) = log(M_.params(35));
oo_.steady_state( 12 ) = log(M_.params(36));
oo_.steady_state( 13 ) = log(M_.params(37));
oo_.steady_state( 14 ) = log(M_.params(38));
oo_.steady_state( 15 ) = log(M_.params(39));
oo_.steady_state( 16 ) = log(M_.params(40));
oo_.steady_state( 17 ) = log(M_.params(41));
oo_.steady_state( 18 ) = log(M_.params(42));
oo_.steady_state( 19 ) = log(M_.params(43));
oo_.steady_state( 20 ) = log(M_.params(44));
oo_.steady_state( 21 ) = log(M_.params(45));
oo_.steady_state( 22 ) = log(M_.params(46));
oo_.steady_state( 23 ) = log(M_.params(47));
oo_.steady_state( 24 ) = log(M_.params(48));
oo_.steady_state( 25 ) = log(M_.params(49));
oo_.steady_state( 26 ) = M_.params(7);
oo_.endo_simul=[oo_.steady_state*ones(1,M_.maximum_lag)];
if M_.exo_nbr > 0;
	oo_.exo_simul = [ones(M_.maximum_lag,1)*oo_.exo_steady_state'];
end;
if M_.exo_det_nbr > 0;
	oo_.exo_det_simul = [ones(M_.maximum_lag,1)*oo_.exo_det_steady_state'];
end;
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = M_.params(19)^2;
M_.Sigma_e(2, 2) = M_.params(20)^2;
M_.Sigma_e(3, 3) = M_.params(21)^2;
M_.Sigma_e(4, 4) = M_.params(22)^2;
M_.sigma_e_is_diagonal = 1;
resid(1);
steady;
check;
options_.order = 1;
var_list_=[];
var_list_ = 'Y';
var_list_ = char(var_list_, 'C');
var_list_ = char(var_list_, 'inv');
var_list_ = char(var_list_, 'N');
var_list_ = char(var_list_, 'i');
var_list_ = char(var_list_, 'pi');
var_list_ = char(var_list_, 'w');
var_list_ = char(var_list_, 'u');
var_list_ = char(var_list_, 'z');
var_list_ = char(var_list_, 'A');
var_list_ = char(var_list_, 'G');
info = stoch_simul(var_list_);
save('mediumdsge_results.mat', 'oo_', 'M_', 'options_');
diary off

disp(['Total computing time : ' dynsec2hms(toc) ]);
