%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_
options_ = [];
M_.fname = 'BRA_SAMBA08';
%
% Some global variables initialization
%
global_initialization;
diary off;
logname_ = 'BRA_SAMBA08.log';
if exist(logname_, 'file')
    delete(logname_)
end
diary(logname_)
M_.exo_names = 'pibar_';
M_.exo_names_tex = 'pibar\_';
M_.exo_names = char(M_.exo_names, 'gbar_');
M_.exo_names_tex = char(M_.exo_names_tex, 'gbar\_');
M_.exo_names = char(M_.exo_names, 'c_');
M_.exo_names_tex = char(M_.exo_names_tex, 'c\_');
M_.exo_names = char(M_.exo_names, 'n_');
M_.exo_names_tex = char(M_.exo_names_tex, 'n\_');
M_.exo_names = char(M_.exo_names, 'i_');
M_.exo_names_tex = char(M_.exo_names_tex, 'i\_');
M_.exo_names = char(M_.exo_names, 'fiistar_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiistar\_');
M_.exo_names = char(M_.exo_names, 'fii_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fii\_');
M_.exo_names = char(M_.exo_names, 'a_');
M_.exo_names_tex = char(M_.exo_names_tex, 'a\_');
M_.exo_names = char(M_.exo_names, 'mstar_');
M_.exo_names_tex = char(M_.exo_names_tex, 'mstar\_');
M_.exo_names = char(M_.exo_names, 'pistar_');
M_.exo_names_tex = char(M_.exo_names_tex, 'pistar\_');
M_.exo_names = char(M_.exo_names, 'rstar_');
M_.exo_names_tex = char(M_.exo_names_tex, 'rstar\_');
M_.exo_names = char(M_.exo_names, 'r_');
M_.exo_names_tex = char(M_.exo_names_tex, 'r\_');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.endo_names = 'co';
M_.endo_names_tex = 'co';
M_.endo_names = char(M_.endo_names, 'crot');
M_.endo_names_tex = char(M_.endo_names_tex, 'crot');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names = char(M_.endo_names, 'no');
M_.endo_names_tex = char(M_.endo_names_tex, 'no');
M_.endo_names = char(M_.endo_names, 'nrot');
M_.endo_names_tex = char(M_.endo_names_tex, 'nrot');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names = char(M_.endo_names, 'wr');
M_.endo_names_tex = char(M_.endo_names_tex, 'wr');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names = char(M_.endo_names, 'fii');
M_.endo_names_tex = char(M_.endo_names_tex, 'fii');
M_.endo_names = char(M_.endo_names, 'qi');
M_.endo_names_tex = char(M_.endo_names_tex, 'qi');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, 'x');
M_.endo_names = char(M_.endo_names, 'm');
M_.endo_names_tex = char(M_.endo_names_tex, 'm');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names = char(M_.endo_names, 'bystar');
M_.endo_names_tex = char(M_.endo_names_tex, 'bystar');
M_.endo_names = char(M_.endo_names, 'nxy');
M_.endo_names_tex = char(M_.endo_names_tex, 'nxy');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names = char(M_.endo_names, 'gy');
M_.endo_names_tex = char(M_.endo_names_tex, 'gy');
M_.endo_names = char(M_.endo_names, 'syhat');
M_.endo_names_tex = char(M_.endo_names_tex, 'syhat');
M_.endo_names = char(M_.endo_names, 'bby');
M_.endo_names_tex = char(M_.endo_names_tex, 'bby');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names = char(M_.endo_names, 'yva');
M_.endo_names_tex = char(M_.endo_names_tex, 'yva');
M_.endo_names = char(M_.endo_names, 'piva');
M_.endo_names_tex = char(M_.endo_names_tex, 'piva');
M_.endo_names = char(M_.endo_names, 'pibar');
M_.endo_names_tex = char(M_.endo_names_tex, 'pibar');
M_.endo_names = char(M_.endo_names, 'sgbar');
M_.endo_names_tex = char(M_.endo_names_tex, 'sgbar');
M_.endo_names = char(M_.endo_names, 'zc');
M_.endo_names_tex = char(M_.endo_names_tex, 'zc');
M_.endo_names = char(M_.endo_names, 'zn');
M_.endo_names_tex = char(M_.endo_names_tex, 'zn');
M_.endo_names = char(M_.endo_names, 'zi');
M_.endo_names_tex = char(M_.endo_names_tex, 'zi');
M_.endo_names = char(M_.endo_names, 'zfiistar');
M_.endo_names_tex = char(M_.endo_names_tex, 'zfiistar');
M_.endo_names = char(M_.endo_names, 'zfii');
M_.endo_names_tex = char(M_.endo_names_tex, 'zfii');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names = char(M_.endo_names, 'zr');
M_.endo_names_tex = char(M_.endo_names_tex, 'zr');
M_.endo_names = char(M_.endo_names, 'zg');
M_.endo_names_tex = char(M_.endo_names_tex, 'zg');
M_.endo_names = char(M_.endo_names, 'mstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'mstar');
M_.endo_names = char(M_.endo_names, 'pistar');
M_.endo_names_tex = char(M_.endo_names_tex, 'pistar');
M_.endo_names = char(M_.endo_names, 'rstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'rstar');
M_.endo_names = char(M_.endo_names, 'g_');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_88');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_88');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_92');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_92');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_96');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_96');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_123');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_123');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_127');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_127');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_131');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_131');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_17_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_17\_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_17_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_17\_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_45_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_45\_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_45_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_45\_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_45_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_45\_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_42_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_42\_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_42_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_42\_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_42_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_42\_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_44_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_44\_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_44_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_44\_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_44_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_44\_3');
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names = char(M_.param_names, 'pessi');
M_.param_names_tex = char(M_.param_names_tex, 'pessi');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names = char(M_.param_names, 'h');
M_.param_names_tex = char(M_.param_names_tex, 'h');
M_.param_names = char(M_.param_names, 'omegabarb');
M_.param_names_tex = char(M_.param_names_tex, 'omegabarb');
M_.param_names = char(M_.param_names, 'tet');
M_.param_names_tex = char(M_.param_names_tex, 'tet');
M_.param_names = char(M_.param_names, 'nuu');
M_.param_names_tex = char(M_.param_names_tex, 'nuu');
M_.param_names = char(M_.param_names, 'kuu');
M_.param_names_tex = char(M_.param_names_tex, 'kuu');
M_.param_names = char(M_.param_names, 'vi');
M_.param_names_tex = char(M_.param_names_tex, 'vi');
M_.param_names = char(M_.param_names, 'del');
M_.param_names_tex = char(M_.param_names_tex, 'del');
M_.param_names = char(M_.param_names, 'dela');
M_.param_names_tex = char(M_.param_names_tex, 'dela');
M_.param_names = char(M_.param_names, 'dels');
M_.param_names_tex = char(M_.param_names_tex, 'dels');
M_.param_names = char(M_.param_names, 'sc');
M_.param_names_tex = char(M_.param_names_tex, 'sc');
M_.param_names = char(M_.param_names, 'si');
M_.param_names_tex = char(M_.param_names_tex, 'si');
M_.param_names = char(M_.param_names, 'sg');
M_.param_names_tex = char(M_.param_names_tex, 'sg');
M_.param_names = char(M_.param_names, 'sm');
M_.param_names_tex = char(M_.param_names_tex, 'sm');
M_.param_names = char(M_.param_names, 'sx');
M_.param_names_tex = char(M_.param_names_tex, 'sx');
M_.param_names = char(M_.param_names, 'sva');
M_.param_names_tex = char(M_.param_names_tex, 'sva');
M_.param_names = char(M_.param_names, 'sd');
M_.param_names_tex = char(M_.param_names_tex, 'sd');
M_.param_names = char(M_.param_names, 'omegabarc');
M_.param_names_tex = char(M_.param_names_tex, 'omegabarc');
M_.param_names = char(M_.param_names, 'omegabarn');
M_.param_names_tex = char(M_.param_names_tex, 'omegabarn');
M_.param_names = char(M_.param_names, 'iok');
M_.param_names_tex = char(M_.param_names_tex, 'iok');
M_.param_names = char(M_.param_names, 'fiistar');
M_.param_names_tex = char(M_.param_names_tex, 'fiistar');
M_.param_names = char(M_.param_names, 'rstarC');
M_.param_names_tex = char(M_.param_names_tex, 'rstarC');
M_.param_names = char(M_.param_names, 'bystarC');
M_.param_names_tex = char(M_.param_names_tex, 'bystarC');
M_.param_names = char(M_.param_names, 'rC');
M_.param_names_tex = char(M_.param_names_tex, 'rC');
M_.param_names = char(M_.param_names, 'byC');
M_.param_names_tex = char(M_.param_names_tex, 'byC');
M_.param_names = char(M_.param_names, 'gamar');
M_.param_names_tex = char(M_.param_names_tex, 'gamar');
M_.param_names = char(M_.param_names, 'gamapi');
M_.param_names_tex = char(M_.param_names_tex, 'gamapi');
M_.param_names = char(M_.param_names, 'gamay');
M_.param_names_tex = char(M_.param_names_tex, 'gamay');
M_.param_names = char(M_.param_names, 'gamag');
M_.param_names_tex = char(M_.param_names_tex, 'gamag');
M_.param_names = char(M_.param_names, 'gamas');
M_.param_names_tex = char(M_.param_names_tex, 'gamas');
M_.param_names = char(M_.param_names, 'gamab');
M_.param_names_tex = char(M_.param_names_tex, 'gamab');
M_.param_names = char(M_.param_names, 'rhoa');
M_.param_names_tex = char(M_.param_names_tex, 'rhoa');
M_.param_names = char(M_.param_names, 'rhoc');
M_.param_names_tex = char(M_.param_names_tex, 'rhoc');
M_.param_names = char(M_.param_names, 'rhoi');
M_.param_names_tex = char(M_.param_names_tex, 'rhoi');
M_.param_names = char(M_.param_names, 'rhon');
M_.param_names_tex = char(M_.param_names_tex, 'rhon');
M_.param_names = char(M_.param_names, 'rhoq');
M_.param_names_tex = char(M_.param_names_tex, 'rhoq');
M_.param_names = char(M_.param_names, 'rhor');
M_.param_names_tex = char(M_.param_names_tex, 'rhor');
M_.param_names = char(M_.param_names, 'rhog');
M_.param_names_tex = char(M_.param_names_tex, 'rhog');
M_.param_names = char(M_.param_names, 'rhosbar');
M_.param_names_tex = char(M_.param_names_tex, 'rhosbar');
M_.param_names = char(M_.param_names, 'rhopi');
M_.param_names_tex = char(M_.param_names_tex, 'rhopi');
M_.param_names = char(M_.param_names, 'rhofii');
M_.param_names_tex = char(M_.param_names_tex, 'rhofii');
M_.param_names = char(M_.param_names, 'rhofiistar');
M_.param_names_tex = char(M_.param_names_tex, 'rhofiistar');
M_.param_names = char(M_.param_names, 'rhomstar');
M_.param_names_tex = char(M_.param_names_tex, 'rhomstar');
M_.param_names = char(M_.param_names, 'rhorstar');
M_.param_names_tex = char(M_.param_names_tex, 'rhorstar');
M_.param_names = char(M_.param_names, 'rhopistar');
M_.param_names_tex = char(M_.param_names_tex, 'rhopistar');
M_.exo_det_nbr = 0;
M_.exo_nbr = 14;
M_.endo_nbr = 65;
M_.param_nbr = 74;
M_.orig_endo_nbr = 48;
M_.aux_vars(1).endo_index = 49;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 50;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 51;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 52;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 53;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 54;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 55;
M_.aux_vars(7).type = 1;
M_.aux_vars(7).orig_index = 18;
M_.aux_vars(7).orig_lead_lag = -1;
M_.aux_vars(8).endo_index = 56;
M_.aux_vars(8).type = 1;
M_.aux_vars(8).orig_index = 18;
M_.aux_vars(8).orig_lead_lag = -2;
M_.aux_vars(9).endo_index = 57;
M_.aux_vars(9).type = 1;
M_.aux_vars(9).orig_index = 46;
M_.aux_vars(9).orig_lead_lag = -1;
M_.aux_vars(10).endo_index = 58;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 46;
M_.aux_vars(10).orig_lead_lag = -2;
M_.aux_vars(11).endo_index = 59;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 46;
M_.aux_vars(11).orig_lead_lag = -3;
M_.aux_vars(12).endo_index = 60;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 43;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 61;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 43;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 62;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 43;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 63;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 45;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 64;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 45;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 65;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 45;
M_.aux_vars(17).orig_lead_lag = -3;
M_.Sigma_e = zeros(14, 14);
M_.H = 0;
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('BRA_SAMBA08_dynamic');
M_.lead_lag_incidence = [
 1 39 104;
 2 40 0;
 0 41 0;
 0 42 0;
 0 43 0;
 0 44 0;
 3 45 105;
 0 46 0;
 4 47 0;
 0 48 0;
 0 49 0;
 0 50 106;
 5 51 107;
 0 52 0;
 0 53 0;
 0 54 108;
 0 55 0;
 6 56 109;
 7 57 0;
 0 58 0;
 0 59 0;
 8 60 0;
 9 61 0;
 10 62 0;
 0 63 0;
 0 64 0;
 11 65 0;
 0 66 0;
 12 67 0;
 13 68 0;
 14 69 0;
 15 70 0;
 16 71 0;
 17 72 0;
 18 73 0;
 19 74 0;
 20 75 0;
 21 76 0;
 22 77 0;
 23 78 110;
 24 79 0;
 0 80 0;
 25 81 0;
 0 82 0;
 26 83 111;
 27 84 112;
 0 85 0;
 0 86 0;
 0 87 113;
 0 88 114;
 0 89 115;
 0 90 116;
 0 91 117;
 0 92 118;
 28 93 0;
 29 94 0;
 30 95 0;
 31 96 0;
 32 97 0;
 33 98 0;
 34 99 0;
 35 100 0;
 36 101 0;
 37 102 0;
 38 103 0;]';
M_.equations_tags = {
};
M_.exo_names_orig_ord = [1:14];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(65, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(14, 1);
M_.params = NaN(74, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 240;
M_.NNZDerivatives(2) = 0;
M_.NNZDerivatives(3) = -1;
M_.params( 26 ) = 0.98;
beta = M_.params( 26 );
M_.params( 27 ) = 0.4;
alpha = M_.params( 27 );
M_.params( 28 ) = 0.823;
sigma = M_.params( 28 );
M_.params( 29 ) = 0.04;
pessi = M_.params( 29 );
M_.params( 30 ) = 1.014;
kappa = M_.params( 30 );
M_.params( 31 ) = 0.218;
h = M_.params( 31 );
M_.params( 32 ) = 0.239;
omegabarb = M_.params( 32 );
M_.params( 33 ) = 0.906;
tet = M_.params( 33 );
M_.params( 34 ) = 0.338;
nuu = M_.params( 34 );
M_.params( 35 ) = 1.406;
kuu = M_.params( 35 );
M_.params( 36 ) = 0.672;
vi = M_.params( 36 );
M_.params( 37 ) = 0.025;
del = M_.params( 37 );
M_.params( 38 ) = 1;
dela = M_.params( 38 );
M_.params( 39 ) = 3.997;
dels = M_.params( 39 );
M_.params( 40 ) = 0.555;
sc = M_.params( 40 );
M_.params( 41 ) = 0.147;
si = M_.params( 41 );
M_.params( 42 ) = 0.176;
sg = M_.params( 42 );
M_.params( 43 ) = 0.109;
sm = M_.params( 43 );
M_.params( 44 ) = 0.121;
sx = M_.params( 44 );
M_.params( 45 ) = 0.891;
sva = M_.params( 45 );
M_.params( 46 ) = 0.891;
sd = M_.params( 46 );
M_.params( 47 ) = 0.4;
omegabarc = M_.params( 47 );
M_.params( 48 ) = 0.8;
omegabarn = M_.params( 48 );
M_.params( 49 ) = 0.03;
iok = M_.params( 49 );
M_.params( 50 ) = 1.016;
fiistar = M_.params( 50 );
M_.params( 51 ) = 1.009;
rstarC = M_.params( 51 );
M_.params( 52 ) = 0.033;
bystarC = M_.params( 52 );
M_.params( 53 ) = 1.042;
rC = M_.params( 53 );
M_.params( 54 ) = 1.028;
byC = M_.params( 54 );
M_.params( 55 ) = 0.682;
gamar = M_.params( 55 );
M_.params( 56 ) = 1.523;
gamapi = M_.params( 56 );
M_.params( 57 ) = 0.839;
gamay = M_.params( 57 );
M_.params( 58 ) = 0.695;
gamag = M_.params( 58 );
M_.params( 59 ) = 0.465;
gamas = M_.params( 59 );
M_.params( 60 ) = 0.17;
gamab = M_.params( 60 );
M_.params( 61 ) = 0.985;
rhoa = M_.params( 61 );
M_.params( 62 ) = 0.7;
rhoc = M_.params( 62 );
M_.params( 63 ) = 0.28;
rhoi = M_.params( 63 );
M_.params( 64 ) = 0.74;
rhon = M_.params( 64 );
M_.params( 65 ) = 0.0;
rhoq = M_.params( 65 );
M_.params( 66 ) = 0.0;
rhor = M_.params( 66 );
M_.params( 67 ) = 0.0;
rhog = M_.params( 67 );
M_.params( 68 ) = 0.915;
rhosbar = M_.params( 68 );
M_.params( 69 ) = 0.937;
rhopi = M_.params( 69 );
M_.params( 70 ) = 0.867;
rhofii = M_.params( 70 );
M_.params( 71 ) = 0.64;
rhofiistar = M_.params( 71 );
M_.params( 72 ) = 0.257;
rhomstar = M_.params( 72 );
M_.params( 73 ) = 0.848;
rhorstar = M_.params( 73 );
M_.params( 74 ) = (-0.139);
rhopistar = M_.params( 74 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:24                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);  
M_.params( 23 ) = 100;
std_r_ = M_.params( 23 );
M_.params( 25 ) = 1;
coffispol = M_.params( 25 );
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 0;
M_.Sigma_e(2, 2) = 0;
M_.Sigma_e(3, 3) = 0.006561;
M_.Sigma_e(4, 4) = 0.000121;
M_.Sigma_e(5, 5) = 0.0576;
M_.Sigma_e(6, 6) = 1.6e-005;
M_.Sigma_e(7, 7) = 1e-006;
M_.Sigma_e(8, 8) = 0.000484;
M_.Sigma_e(9, 9) = 0.000169;
M_.Sigma_e(10, 10) = 4.000000000000001e-006;
M_.Sigma_e(11, 11) = 0;
M_.Sigma_e(12, 12) = 9e-006;
M_.Sigma_e(14, 14) = 2.5e-005;
M_.sigma_e_is_diagonal = 1;
save('BRA_SAMBA08_results.mat', 'oo_', 'M_', 'options_');
diary off

disp(['Total computing time : ' dynsec2hms(toc) ]);
