%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_
options_ = [];
M_.fname = 'NK_sticky_taylor';
%
% Some global variables initialization
%
global_initialization;
diary off;
logname_ = 'NK_sticky_taylor.log';
if exist(logname_, 'file')
    delete(logname_)
end
diary(logname_)
M_.exo_names = 'ea';
M_.exo_names_tex = 'ea';
M_.exo_names = char(M_.exo_names, 'ei');
M_.exo_names_tex = char(M_.exo_names_tex, 'ei');
M_.endo_names = 'c';
M_.endo_names_tex = 'c';
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names = char(M_.endo_names, 'vp');
M_.endo_names_tex = char(M_.endo_names_tex, 'vp');
M_.endo_names = char(M_.endo_names, 'pisharp');
M_.endo_names_tex = char(M_.endo_names_tex, 'pisharp');
M_.endo_names = char(M_.endo_names, 'x1');
M_.endo_names_tex = char(M_.endo_names_tex, 'x1');
M_.endo_names = char(M_.endo_names, 'x2');
M_.endo_names_tex = char(M_.endo_names_tex, 'x2');
M_.endo_names = char(M_.endo_names, 'yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'yf');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names = char(M_.endo_names, 'm');
M_.endo_names_tex = char(M_.endo_names_tex, 'm');
M_.param_names = 'sigma';
M_.param_names_tex = 'sigma';
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names = char(M_.param_names, 'psi');
M_.param_names_tex = char(M_.param_names_tex, 'psi');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names = char(M_.param_names, 'phipi');
M_.param_names_tex = char(M_.param_names_tex, 'phipi');
M_.param_names = char(M_.param_names, 'phiy');
M_.param_names_tex = char(M_.param_names_tex, 'phiy');
M_.param_names = char(M_.param_names, 'rhoa');
M_.param_names_tex = char(M_.param_names_tex, 'rhoa');
M_.param_names = char(M_.param_names, 'rhoi');
M_.param_names_tex = char(M_.param_names_tex, 'rhoi');
M_.param_names = char(M_.param_names, 'sigmaa');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaa');
M_.param_names = char(M_.param_names, 'sigmam');
M_.param_names_tex = char(M_.param_names_tex, 'sigmam');
M_.param_names = char(M_.param_names, 'cs');
M_.param_names_tex = char(M_.param_names_tex, 'cs');
M_.param_names = char(M_.param_names, 'is');
M_.param_names_tex = char(M_.param_names_tex, 'is');
M_.param_names = char(M_.param_names, 'pis');
M_.param_names_tex = char(M_.param_names_tex, 'pis');
M_.param_names = char(M_.param_names, 'ns');
M_.param_names_tex = char(M_.param_names_tex, 'ns');
M_.param_names = char(M_.param_names, 'ws');
M_.param_names_tex = char(M_.param_names_tex, 'ws');
M_.param_names = char(M_.param_names, 'mcs');
M_.param_names_tex = char(M_.param_names_tex, 'mcs');
M_.param_names = char(M_.param_names, 'as');
M_.param_names_tex = char(M_.param_names_tex, 'as');
M_.param_names = char(M_.param_names, 'ys');
M_.param_names_tex = char(M_.param_names_tex, 'ys');
M_.param_names = char(M_.param_names, 'vps');
M_.param_names_tex = char(M_.param_names_tex, 'vps');
M_.param_names = char(M_.param_names, 'pisharps');
M_.param_names_tex = char(M_.param_names_tex, 'pisharps');
M_.param_names = char(M_.param_names, 'x1s');
M_.param_names_tex = char(M_.param_names_tex, 'x1s');
M_.param_names = char(M_.param_names, 'x2s');
M_.param_names_tex = char(M_.param_names_tex, 'x2s');
M_.param_names = char(M_.param_names, 'yfs');
M_.param_names_tex = char(M_.param_names_tex, 'yfs');
M_.param_names = char(M_.param_names, 'outputgaps');
M_.param_names_tex = char(M_.param_names_tex, 'outputgaps');
M_.param_names = char(M_.param_names, 'ms');
M_.param_names_tex = char(M_.param_names_tex, 'ms');
M_.exo_det_nbr = 0;
M_.exo_nbr = 2;
M_.endo_nbr = 16;
M_.param_nbr = 28;
M_.orig_endo_nbr = 16;
M_.aux_vars = [];
M_.Sigma_e = zeros(2, 2);
M_.H = 0;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('NK_sticky_taylor_dynamic');
M_.lead_lag_incidence = [
 0 4 20;
 1 5 0;
 0 6 21;
 0 7 0;
 0 8 0;
 0 9 0;
 0 10 0;
 2 11 0;
 0 12 0;
 3 13 0;
 0 14 0;
 0 15 22;
 0 16 23;
 0 17 0;
 0 18 0;
 0 19 0;]';
M_.equations_tags = {
};
M_.exo_names_orig_ord = [1:2];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(16, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(2, 1);
M_.params = repmat(NaN,28, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 56;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
M_.params( 2 ) = .99;
beta = M_.params( 2 );
M_.params( 1 ) = 1;
sigma = M_.params( 1 );
M_.params( 4 ) = 1;
eta = M_.params( 4 );
M_.params( 3 ) = 1;
psi = M_.params( 3 );
M_.params( 6 ) = 10;
epsilon = M_.params( 6 );
M_.params( 7 ) = 1;
theta = M_.params( 7 );
M_.params( 8 ) = 1.5;
phipi = M_.params( 8 );
M_.params( 9 ) = 0;
phiy = M_.params( 9 );
M_.params( 10 ) = .95;
rhoa = M_.params( 10 );
M_.params( 11 ) = 0.8;
rhoi = M_.params( 11 );
M_.params( 12 ) = .01;
sigmaa = M_.params( 12 );
M_.params( 13 ) = .01;
sigmam = M_.params( 13 );
M_.params( 5 ) = .75;
phi = M_.params( 5 );
M_.params( 15 ) = 1/M_.params(2);
is = M_.params( 15 );
M_.params( 20 ) = 1;
as = M_.params( 20 );
M_.params( 16 ) = 1;
pis = M_.params( 16 );
M_.params( 23 ) = ((M_.params(16)^(1-M_.params(6))-M_.params(5))/(1-M_.params(5)))^(1/(1-M_.params(6)));
pisharps = M_.params( 23 );
M_.params( 22 ) = (1-M_.params(5))*(M_.params(16)/M_.params(23))^M_.params(6)/(1-M_.params(5)*M_.params(16)^M_.params(6));
vps = M_.params( 22 );
M_.params( 19 ) = (M_.params(6)-1)*M_.params(16)*(1-M_.params(16)^M_.params(6)*M_.params(2)*M_.params(5))/(1-M_.params(2)*M_.params(5)*M_.params(16)^(M_.params(6)-1))/M_.params(23)/M_.params(6);
mcs = M_.params( 19 );
M_.params( 17 ) = (M_.params(22)^M_.params(1)*M_.params(19)/M_.params(3))^(1/(M_.params(1)+M_.params(4)));
ns = M_.params( 17 );
M_.params( 21 ) = M_.params(20)*M_.params(17)/M_.params(22);
ys = M_.params( 21 );
M_.params( 14 ) = M_.params(21);
cs = M_.params( 14 );
M_.params( 26 ) = ((M_.params(6)-1)/M_.params(6)/M_.params(3))^(1/(M_.params(1)+M_.params(4)))*M_.params(20)^((1+M_.params(4))/(M_.params(1)+M_.params(4)));
yfs = M_.params( 26 );
M_.params( 27 ) = M_.params(21)/M_.params(26);
outputgaps = M_.params( 27 );
M_.params( 18 ) = M_.params(19)*M_.params(20);
ws = M_.params( 18 );
M_.params( 24 ) = M_.params(21)*M_.params(19)*M_.params(14)^(-M_.params(1))/(1-M_.params(16)^M_.params(6)*M_.params(2)*M_.params(5));
x1s = M_.params( 24 );
M_.params( 25 ) = M_.params(21)*M_.params(14)^(-M_.params(1))/(1-M_.params(2)*M_.params(5)*M_.params(16)^(M_.params(6)-1));
x2s = M_.params( 25 );
M_.params( 28 ) = M_.params(7)*M_.params(15)/(M_.params(15)-1)*M_.params(14)^M_.params(1);
ms = M_.params( 28 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 1 ) = log(M_.params(14));
oo_.steady_state( 2 ) = log(M_.params(15));
oo_.steady_state( 3 ) = log(M_.params(16));
oo_.steady_state( 5 ) = log(M_.params(17));
oo_.steady_state( 6 ) = log(M_.params(18));
oo_.steady_state( 7 ) = log(M_.params(19));
oo_.steady_state( 8 ) = log(M_.params(20));
oo_.steady_state( 9 ) = log(M_.params(21));
oo_.steady_state( 10 ) = log(M_.params(22));
oo_.steady_state( 11 ) = log(M_.params(23));
oo_.steady_state( 12 ) = log(M_.params(24));
oo_.steady_state( 13 ) = log(M_.params(25));
oo_.steady_state( 14 ) = log(M_.params(26));
oo_.steady_state( 15 ) = log(M_.params(27));
oo_.steady_state( 4 ) = log(M_.params(15)/M_.params(16));
oo_.steady_state( 16 ) = log(M_.params(28));
oo_.endo_simul=[oo_.steady_state*ones(1,M_.maximum_lag)];
if M_.exo_nbr > 0;
	oo_.exo_simul = [ones(M_.maximum_lag,1)*oo_.exo_steady_state'];
end;
if M_.exo_det_nbr > 0;
	oo_.exo_det_simul = [ones(M_.maximum_lag,1)*oo_.exo_det_steady_state'];
end;
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 0.0001;
M_.Sigma_e(2, 2) = 0.0001;
M_.sigma_e_is_diagonal = 1;
resid(1);
steady;
check;
options_.order = 1;
var_list_=[];
var_list_ = 'm';
var_list_ = char(var_list_, 'i');
var_list_ = char(var_list_, 'pi');
var_list_ = char(var_list_, 'n');
var_list_ = char(var_list_, 'w');
var_list_ = char(var_list_, 'mc');
var_list_ = char(var_list_, 'y');
var_list_ = char(var_list_, 'yf');
var_list_ = char(var_list_, 'r');
var_list_ = char(var_list_, 'outputgap');
var_list_ = char(var_list_, 'a');
info = stoch_simul(var_list_);
save('NK_sticky_taylor_results.mat', 'oo_', 'M_', 'options_');
diary off

disp(['Total computing time : ' dynsec2hms(toc) ]);
