%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_
options_ = [];
M_.fname = 'EA_SW03';
%
% Some global variables initialization
%
global_initialization;
diary off;
logname_ = 'EA_SW03.log';
if exist(logname_, 'file')
    delete(logname_)
end
diary(logname_)
M_.exo_names = 'ea';
M_.exo_names_tex = 'ea';
M_.exo_names = char(M_.exo_names, 'eb');
M_.exo_names_tex = char(M_.exo_names_tex, 'eb');
M_.exo_names = char(M_.exo_names, 'y_');
M_.exo_names_tex = char(M_.exo_names_tex, 'y\_');
M_.exo_names = char(M_.exo_names, 'els');
M_.exo_names_tex = char(M_.exo_names_tex, 'els');
M_.exo_names = char(M_.exo_names, 'eqs');
M_.exo_names_tex = char(M_.exo_names_tex, 'eqs');
M_.exo_names = char(M_.exo_names, 'eps');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps');
M_.exo_names = char(M_.exo_names, 'eas');
M_.exo_names_tex = char(M_.exo_names_tex, 'eas');
M_.exo_names = char(M_.exo_names, 'econs');
M_.exo_names_tex = char(M_.exo_names_tex, 'econs');
M_.exo_names = char(M_.exo_names, 'einv');
M_.exo_names_tex = char(M_.exo_names_tex, 'einv');
M_.exo_names = char(M_.exo_names, 'ey');
M_.exo_names_tex = char(M_.exo_names_tex, 'ey');
M_.exo_names = char(M_.exo_names, 'elab');
M_.exo_names_tex = char(M_.exo_names_tex, 'elab');
M_.exo_names = char(M_.exo_names, 'epinf');
M_.exo_names_tex = char(M_.exo_names_tex, 'epinf');
M_.exo_names = char(M_.exo_names, 'ew');
M_.exo_names_tex = char(M_.exo_names_tex, 'ew');
M_.exo_names = char(M_.exo_names, 'em');
M_.exo_names_tex = char(M_.exo_names_tex, 'em');
M_.exo_names = char(M_.exo_names, 'er');
M_.exo_names_tex = char(M_.exo_names_tex, 'er');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.endo_names = 'mcf';
M_.endo_names_tex = 'mcf';
M_.endo_names = char(M_.endo_names, 'zcapf');
M_.endo_names_tex = char(M_.endo_names_tex, 'zcapf');
M_.endo_names = char(M_.endo_names, 'rkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkf');
M_.endo_names = char(M_.endo_names, 'kf');
M_.endo_names_tex = char(M_.endo_names_tex, 'kf');
M_.endo_names = char(M_.endo_names, 'pkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pkf');
M_.endo_names = char(M_.endo_names, 'muf');
M_.endo_names_tex = char(M_.endo_names_tex, 'muf');
M_.endo_names = char(M_.endo_names, 'cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cf');
M_.endo_names = char(M_.endo_names, 'invef');
M_.endo_names_tex = char(M_.endo_names_tex, 'invef');
M_.endo_names = char(M_.endo_names, 'yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'yf');
M_.endo_names = char(M_.endo_names, 'labf');
M_.endo_names_tex = char(M_.endo_names_tex, 'labf');
M_.endo_names = char(M_.endo_names, 'pinff');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinff');
M_.endo_names = char(M_.endo_names, 'wf');
M_.endo_names_tex = char(M_.endo_names_tex, 'wf');
M_.endo_names = char(M_.endo_names, 'pf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pf');
M_.endo_names = char(M_.endo_names, 'emplf');
M_.endo_names_tex = char(M_.endo_names_tex, 'emplf');
M_.endo_names = char(M_.endo_names, 'rrf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rrf');
M_.endo_names = char(M_.endo_names, 'effortf');
M_.endo_names_tex = char(M_.endo_names_tex, 'effortf');
M_.endo_names = char(M_.endo_names, 'rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rf');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names = char(M_.endo_names, 'zcap');
M_.endo_names_tex = char(M_.endo_names_tex, 'zcap');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names = char(M_.endo_names, 'pk');
M_.endo_names_tex = char(M_.endo_names_tex, 'pk');
M_.endo_names = char(M_.endo_names, 'mu');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names = char(M_.endo_names, 'inve');
M_.endo_names_tex = char(M_.endo_names_tex, 'inve');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names = char(M_.endo_names, 'lab');
M_.endo_names_tex = char(M_.endo_names_tex, 'lab');
M_.endo_names = char(M_.endo_names, 'pinf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinf');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names = char(M_.endo_names, 'p');
M_.endo_names_tex = char(M_.endo_names_tex, 'p');
M_.endo_names = char(M_.endo_names, 'empl');
M_.endo_names_tex = char(M_.endo_names_tex, 'empl');
M_.endo_names = char(M_.endo_names, 'ww');
M_.endo_names_tex = char(M_.endo_names_tex, 'ww');
M_.endo_names = char(M_.endo_names, 'effort');
M_.endo_names_tex = char(M_.endo_names_tex, 'effort');
M_.endo_names = char(M_.endo_names, 'pinf4');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinf4');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names = char(M_.endo_names, 'dr');
M_.endo_names_tex = char(M_.endo_names_tex, 'dr');
M_.endo_names = char(M_.endo_names, 'pinfLAG1');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinfLAG1');
M_.endo_names = char(M_.endo_names, 'pinfLAG2');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinfLAG2');
M_.endo_names = char(M_.endo_names, 'ygap');
M_.endo_names_tex = char(M_.endo_names_tex, 'ygap');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names = char(M_.endo_names, 'as');
M_.endo_names_tex = char(M_.endo_names_tex, 'as');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names = char(M_.endo_names, 'ls');
M_.endo_names_tex = char(M_.endo_names_tex, 'ls');
M_.endo_names = char(M_.endo_names, 'qs');
M_.endo_names_tex = char(M_.endo_names_tex, 'qs');
M_.endo_names = char(M_.endo_names, 'ps');
M_.endo_names_tex = char(M_.endo_names_tex, 'ps');
M_.endo_names = char(M_.endo_names, 'ms');
M_.endo_names_tex = char(M_.endo_names_tex, 'ms');
M_.endo_names = char(M_.endo_names, 'scons');
M_.endo_names_tex = char(M_.endo_names_tex, 'scons');
M_.endo_names = char(M_.endo_names, 'sinv');
M_.endo_names_tex = char(M_.endo_names_tex, 'sinv');
M_.endo_names = char(M_.endo_names, 'sy');
M_.endo_names_tex = char(M_.endo_names_tex, 'sy');
M_.endo_names = char(M_.endo_names, 'slab');
M_.endo_names_tex = char(M_.endo_names_tex, 'slab');
M_.endo_names = char(M_.endo_names, 'spinf');
M_.endo_names_tex = char(M_.endo_names_tex, 'spinf');
M_.endo_names = char(M_.endo_names, 'sw');
M_.endo_names_tex = char(M_.endo_names_tex, 'sw');
M_.endo_names = char(M_.endo_names, 'kpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'kpf');
M_.endo_names = char(M_.endo_names, 'habf');
M_.endo_names_tex = char(M_.endo_names_tex, 'habf');
M_.endo_names = char(M_.endo_names, 'kp');
M_.endo_names_tex = char(M_.endo_names_tex, 'kp');
M_.endo_names = char(M_.endo_names, 'hab');
M_.endo_names_tex = char(M_.endo_names_tex, 'hab');
M_.endo_names = char(M_.endo_names, 'one');
M_.endo_names_tex = char(M_.endo_names_tex, 'one');
M_.endo_names = char(M_.endo_names, 'eg');
M_.endo_names_tex = char(M_.endo_names_tex, 'eg');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_72');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_72');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_76');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_76');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_80');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_80');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_107');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_107');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_111');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_111');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_115');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_115');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_62_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_62\_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_62_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_62\_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_62_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_62\_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_59_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_59\_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_59_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_59\_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_59_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_59\_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_61_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_61\_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_61_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_61\_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_61_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_61\_3');
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names = char(M_.param_names, 'calfa');
M_.param_names_tex = char(M_.param_names_tex, 'calfa');
M_.param_names = char(M_.param_names, 'ctou');
M_.param_names_tex = char(M_.param_names_tex, 'ctou');
M_.param_names = char(M_.param_names, 'cbeta');
M_.param_names_tex = char(M_.param_names_tex, 'cbeta');
M_.param_names = char(M_.param_names, 'chab');
M_.param_names_tex = char(M_.param_names_tex, 'chab');
M_.param_names = char(M_.param_names, 'ccs');
M_.param_names_tex = char(M_.param_names_tex, 'ccs');
M_.param_names = char(M_.param_names, 'cinvs');
M_.param_names_tex = char(M_.param_names_tex, 'cinvs');
M_.param_names = char(M_.param_names, 'crelwage');
M_.param_names_tex = char(M_.param_names_tex, 'crelwage');
M_.param_names = char(M_.param_names, 'chabw');
M_.param_names_tex = char(M_.param_names_tex, 'chabw');
M_.param_names = char(M_.param_names, 'clabeff');
M_.param_names_tex = char(M_.param_names_tex, 'clabeff');
M_.param_names = char(M_.param_names, 'chlab');
M_.param_names_tex = char(M_.param_names_tex, 'chlab');
M_.param_names = char(M_.param_names, 'csadjcost');
M_.param_names_tex = char(M_.param_names_tex, 'csadjcost');
M_.param_names = char(M_.param_names, 'csigma');
M_.param_names_tex = char(M_.param_names_tex, 'csigma');
M_.param_names = char(M_.param_names, 'chabb');
M_.param_names_tex = char(M_.param_names_tex, 'chabb');
M_.param_names = char(M_.param_names, 'cprobw');
M_.param_names_tex = char(M_.param_names_tex, 'cprobw');
M_.param_names = char(M_.param_names, 'clandaw');
M_.param_names_tex = char(M_.param_names_tex, 'clandaw');
M_.param_names = char(M_.param_names, 'csigl');
M_.param_names_tex = char(M_.param_names_tex, 'csigl');
M_.param_names = char(M_.param_names, 'cprobp');
M_.param_names_tex = char(M_.param_names_tex, 'cprobp');
M_.param_names = char(M_.param_names, 'cindw');
M_.param_names_tex = char(M_.param_names_tex, 'cindw');
M_.param_names = char(M_.param_names, 'cindp');
M_.param_names_tex = char(M_.param_names_tex, 'cindp');
M_.param_names = char(M_.param_names, 'cfc');
M_.param_names_tex = char(M_.param_names_tex, 'cfc');
M_.param_names = char(M_.param_names, 'cinvdyn');
M_.param_names_tex = char(M_.param_names_tex, 'cinvdyn');
M_.param_names = char(M_.param_names, 'czcap');
M_.param_names_tex = char(M_.param_names_tex, 'czcap');
M_.param_names = char(M_.param_names, 'csadjlab');
M_.param_names_tex = char(M_.param_names_tex, 'csadjlab');
M_.param_names = char(M_.param_names, 'crpi');
M_.param_names_tex = char(M_.param_names_tex, 'crpi');
M_.param_names = char(M_.param_names, 'crdpi');
M_.param_names_tex = char(M_.param_names_tex, 'crdpi');
M_.param_names = char(M_.param_names, 'crr');
M_.param_names_tex = char(M_.param_names_tex, 'crr');
M_.param_names = char(M_.param_names, 'cry');
M_.param_names_tex = char(M_.param_names_tex, 'cry');
M_.param_names = char(M_.param_names, 'crdy');
M_.param_names_tex = char(M_.param_names_tex, 'crdy');
M_.param_names = char(M_.param_names, 'crhoa');
M_.param_names_tex = char(M_.param_names_tex, 'crhoa');
M_.param_names = char(M_.param_names, 'crhoas');
M_.param_names_tex = char(M_.param_names_tex, 'crhoas');
M_.param_names = char(M_.param_names, 'crhob');
M_.param_names_tex = char(M_.param_names_tex, 'crhob');
M_.param_names = char(M_.param_names, 'crhog');
M_.param_names_tex = char(M_.param_names_tex, 'crhog');
M_.param_names = char(M_.param_names, 'crhols');
M_.param_names_tex = char(M_.param_names_tex, 'crhols');
M_.param_names = char(M_.param_names, 'crhoqs');
M_.param_names_tex = char(M_.param_names_tex, 'crhoqs');
M_.param_names = char(M_.param_names, 'crhops');
M_.param_names_tex = char(M_.param_names_tex, 'crhops');
M_.param_names = char(M_.param_names, 'crhoms');
M_.param_names_tex = char(M_.param_names_tex, 'crhoms');
M_.param_names = char(M_.param_names, 'crhoy');
M_.param_names_tex = char(M_.param_names_tex, 'crhoy');
M_.param_names = char(M_.param_names, 'crhocons');
M_.param_names_tex = char(M_.param_names_tex, 'crhocons');
M_.param_names = char(M_.param_names, 'crhoinv');
M_.param_names_tex = char(M_.param_names_tex, 'crhoinv');
M_.param_names = char(M_.param_names, 'crhopinf');
M_.param_names_tex = char(M_.param_names_tex, 'crhopinf');
M_.param_names = char(M_.param_names, 'crhow');
M_.param_names_tex = char(M_.param_names_tex, 'crhow');
M_.param_names = char(M_.param_names, 'crholab');
M_.param_names_tex = char(M_.param_names_tex, 'crholab');
M_.param_names = char(M_.param_names, 'cscaleea');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleea');
M_.param_names = char(M_.param_names, 'cscaleeas');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleeas');
M_.param_names = char(M_.param_names, 'cscaleeb');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleeb');
M_.param_names = char(M_.param_names, 'cscaleeg');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleeg');
M_.param_names = char(M_.param_names, 'cscaleels');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleels');
M_.param_names = char(M_.param_names, 'cscaleeqs');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleeqs');
M_.param_names = char(M_.param_names, 'cscaleeps');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleeps');
M_.param_names = char(M_.param_names, 'cscaleem');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleem');
M_.param_names = char(M_.param_names, 'cscaleecons');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleecons');
M_.param_names = char(M_.param_names, 'cscaleeinv');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleeinv');
M_.param_names = char(M_.param_names, 'cscaleey');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleey');
M_.param_names = char(M_.param_names, 'cscaleelab');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleelab');
M_.param_names = char(M_.param_names, 'cscaleepinf');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleepinf');
M_.param_names = char(M_.param_names, 'cscaleew');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleew');
M_.param_names = char(M_.param_names, 'cscaleer');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleer');
M_.exo_det_nbr = 0;
M_.exo_nbr = 17;
M_.endo_nbr = 80;
M_.param_nbr = 82;
M_.orig_endo_nbr = 65;
M_.aux_vars(1).endo_index = 66;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 67;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 68;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 69;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 70;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 71;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 72;
M_.aux_vars(7).type = 1;
M_.aux_vars(7).orig_index = 63;
M_.aux_vars(7).orig_lead_lag = -1;
M_.aux_vars(8).endo_index = 73;
M_.aux_vars(8).type = 1;
M_.aux_vars(8).orig_index = 63;
M_.aux_vars(8).orig_lead_lag = -2;
M_.aux_vars(9).endo_index = 74;
M_.aux_vars(9).type = 1;
M_.aux_vars(9).orig_index = 63;
M_.aux_vars(9).orig_lead_lag = -3;
M_.aux_vars(10).endo_index = 75;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 60;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 76;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 60;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 77;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 60;
M_.aux_vars(12).orig_lead_lag = -3;
M_.aux_vars(13).endo_index = 78;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 62;
M_.aux_vars(13).orig_lead_lag = -1;
M_.aux_vars(14).endo_index = 79;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 62;
M_.aux_vars(14).orig_lead_lag = -2;
M_.aux_vars(15).endo_index = 80;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 62;
M_.aux_vars(15).orig_lead_lag = -3;
M_.Sigma_e = zeros(17, 17);
M_.H = 0;
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('EA_SW03_dynamic');
M_.lead_lag_incidence = [
 0 43 0;
 0 44 0;
 0 45 123;
 0 46 0;
 0 47 124;
 0 48 125;
 1 49 0;
 2 50 126;
 0 51 0;
 0 52 0;
 0 53 127;
 0 54 0;
 0 55 0;
 3 56 128;
 0 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 129;
 0 63 0;
 0 64 130;
 0 65 131;
 4 66 0;
 5 67 132;
 0 68 0;
 6 69 0;
 7 70 133;
 8 71 134;
 0 72 0;
 9 73 135;
 0 74 0;
 0 75 0;
 0 76 0;
 10 77 0;
 0 78 0;
 11 79 0;
 12 80 0;
 0 81 0;
 13 82 136;
 14 83 0;
 15 84 0;
 16 85 0;
 17 86 0;
 18 87 0;
 19 88 0;
 20 89 0;
 21 90 0;
 22 91 0;
 23 92 0;
 24 93 0;
 25 94 0;
 26 95 0;
 27 96 0;
 28 97 0;
 29 98 0;
 30 99 0;
 0 100 0;
 0 101 0;
 31 102 0;
 0 103 0;
 32 104 137;
 33 105 138;
 0 106 0;
 0 107 0;
 0 108 139;
 0 109 140;
 0 110 141;
 0 111 142;
 0 112 143;
 0 113 144;
 34 114 0;
 35 115 0;
 36 116 0;
 37 117 0;
 38 118 0;
 39 119 0;
 40 120 0;
 41 121 0;
 42 122 0;]';
M_.equations_tags = {
};
M_.exo_names_orig_ord = [1:17];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(80, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(17, 1);
M_.params = repmat(NaN,82, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 273;
M_.NNZDerivatives(2) = 0;
M_.NNZDerivatives(3) = -1;
M_.params( 26 ) = 0.3;
calfa = M_.params( 26 );
M_.params( 27 ) = 0.025;
ctou = M_.params( 27 );
M_.params( 28 ) = 0.99;
cbeta = M_.params( 28 );
M_.params( 29 ) = 0;
chab = M_.params( 29 );
M_.params( 30 ) = 0.6;
ccs = M_.params( 30 );
M_.params( 31 ) = 0.22;
cinvs = M_.params( 31 );
M_.params( 32 ) = 0;
crelwage = M_.params( 32 );
M_.params( 33 ) = 0;
chabw = M_.params( 33 );
M_.params( 34 ) = 0;
clabeff = M_.params( 34 );
M_.params( 35 ) = 0;
chlab = M_.params( 35 );
M_.params( 36 ) = 6.7711;
csadjcost = M_.params( 36 );
M_.params( 37 ) = 1.3533;
csigma = M_.params( 37 );
M_.params( 38 ) = 0.5732;
chabb = M_.params( 38 );
M_.params( 39 ) = 0.7367;
cprobw = M_.params( 39 );
M_.params( 40 ) = 1.5;
clandaw = M_.params( 40 );
M_.params( 41 ) = 2.3995;
csigl = M_.params( 41 );
M_.params( 42 ) = 0.9082;
cprobp = M_.params( 42 );
M_.params( 43 ) = 0.7627;
cindw = M_.params( 43 );
M_.params( 44 ) = 0.4694;
cindp = M_.params( 44 );
M_.params( 45 ) = 1.4077;
cfc = M_.params( 45 );
M_.params( 46 ) = 1;
cinvdyn = M_.params( 46 );
M_.params( 47 ) = 0.1690;
czcap = M_.params( 47 );
M_.params( 48 ) = 0.5990;
csadjlab = M_.params( 48 );
M_.params( 49 ) = 1.6841;
crpi = M_.params( 49 );
M_.params( 50 ) = 0.1398;
crdpi = M_.params( 50 );
M_.params( 51 ) = 0.9613;
crr = M_.params( 51 );
M_.params( 52 ) = 0.0988;
cry = M_.params( 52 );
M_.params( 53 ) = 0.1586;
crdy = M_.params( 53 );
M_.params( 54 ) = 0.8232;
crhoa = M_.params( 54 );
M_.params( 55 ) = 0.9238;
crhoas = M_.params( 55 );
M_.params( 56 ) = 0.8545;
crhob = M_.params( 56 );
M_.params( 57 ) = 0.9493;
crhog = M_.params( 57 );
M_.params( 58 ) = 0.8894;
crhols = M_.params( 58 );
M_.params( 59 ) = 0.9273;
crhoqs = M_.params( 59 );
M_.params( 60 ) = 0;
crhops = M_.params( 60 );
M_.params( 61 ) = 0;
crhoms = M_.params( 61 );
M_.params( 62 ) = 0;
crhoy = M_.params( 62 );
M_.params( 63 ) = 0;
crhocons = M_.params( 63 );
M_.params( 64 ) = 0;
crhoinv = M_.params( 64 );
M_.params( 65 ) = 0;
crhopinf = M_.params( 65 );
M_.params( 66 ) = 0;
crhow = M_.params( 66 );
M_.params( 67 ) = 0;
crholab = M_.params( 67 );
M_.params( 68 ) = 0.5978;
cscaleea = M_.params( 68 );
M_.params( 69 ) = 0.0165;
cscaleeas = M_.params( 69 );
M_.params( 70 ) = 0.3361;
cscaleeb = M_.params( 70 );
M_.params( 71 ) = 0.3247;
cscaleeg = M_.params( 71 );
M_.params( 72 ) = 3.5197;
cscaleels = M_.params( 72 );
M_.params( 73 ) = 0.0851;
cscaleeqs = M_.params( 73 );
M_.params( 74 ) = 0;
cscaleeps = M_.params( 74 );
M_.params( 75 ) = 0.0808;
cscaleem = M_.params( 75 );
M_.params( 76 ) = 0;
cscaleecons = M_.params( 76 );
M_.params( 77 ) = 0.6043;
cscaleeinv = M_.params( 77 );
M_.params( 78 ) = 0;
cscaleey = M_.params( 78 );
M_.params( 79 ) = 0;
cscaleelab = M_.params( 79 );
M_.params( 80 ) = 0.1602;
cscaleepinf = M_.params( 80 );
M_.params( 81 ) = 0.2892;
cscaleew = M_.params( 81 );
M_.params( 82 ) = 0.081;
cscaleer = M_.params( 82 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:24                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);                                                            
M_.params( 25 ) = 1/M_.params(71);
coffispol = M_.params( 25 );
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1;
M_.Sigma_e(2, 2) = 1;
M_.Sigma_e(4, 4) = 1;
M_.Sigma_e(5, 5) = 1;
M_.Sigma_e(7, 7) = 1;
M_.Sigma_e(8, 8) = 1;
M_.Sigma_e(9, 9) = 1;
M_.Sigma_e(10, 10) = 1;
M_.Sigma_e(11, 11) = 1;
M_.Sigma_e(12, 12) = 1;
M_.Sigma_e(13, 13) = 1;
M_.Sigma_e(14, 14) = 1;
M_.Sigma_e(15, 15) = 1;
M_.Sigma_e(17, 17) = M_.params(71)^2;
M_.sigma_e_is_diagonal = 1;
save('EA_SW03_results.mat', 'oo_', 'M_', 'options_');
diary off

disp(['Total computing time : ' dynsec2hms(toc) ]);
