%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'ZLB_eight';
%
% Some global variables initialization
%
global_initialization;
diary off;
M_.exo_names = 'ea';
M_.exo_names_tex = 'ea';
M_.exo_names_long = 'ea';
M_.exo_names = char(M_.exo_names, 'ei');
M_.exo_names_tex = char(M_.exo_names_tex, 'ei');
M_.exo_names_long = char(M_.exo_names_long, 'ei');
M_.exo_names = char(M_.exo_names, 'eg');
M_.exo_names_tex = char(M_.exo_names_tex, 'eg');
M_.exo_names_long = char(M_.exo_names_long, 'eg');
M_.exo_names = char(M_.exo_names, 'ex');
M_.exo_names_tex = char(M_.exo_names_tex, 'ex');
M_.exo_names_long = char(M_.exo_names_long, 'ex');
M_.endo_names = 'c';
M_.endo_names_tex = 'c';
M_.endo_names_long = 'c';
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'vp');
M_.endo_names_tex = char(M_.endo_names_tex, 'vp');
M_.endo_names_long = char(M_.endo_names_long, 'vp');
M_.endo_names = char(M_.endo_names, 'yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'yf');
M_.endo_names_long = char(M_.endo_names_long, 'yf');
M_.endo_names = char(M_.endo_names, 'pisharp');
M_.endo_names_tex = char(M_.endo_names_tex, 'pisharp');
M_.endo_names_long = char(M_.endo_names_long, 'pisharp');
M_.endo_names = char(M_.endo_names, 'x1');
M_.endo_names_tex = char(M_.endo_names_tex, 'x1');
M_.endo_names_long = char(M_.endo_names_long, 'x1');
M_.endo_names = char(M_.endo_names, 'x2');
M_.endo_names_tex = char(M_.endo_names_tex, 'x2');
M_.endo_names_long = char(M_.endo_names_long, 'x2');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'nex');
M_.endo_names_tex = char(M_.endo_names_tex, 'nex');
M_.endo_names_long = char(M_.endo_names_long, 'nex');
M_.endo_names = char(M_.endo_names, 's1');
M_.endo_names_tex = char(M_.endo_names_tex, 's1');
M_.endo_names_long = char(M_.endo_names_long, 's1');
M_.endo_names = char(M_.endo_names, 's2');
M_.endo_names_tex = char(M_.endo_names_tex, 's2');
M_.endo_names_long = char(M_.endo_names_long, 's2');
M_.endo_names = char(M_.endo_names, 's3');
M_.endo_names_tex = char(M_.endo_names_tex, 's3');
M_.endo_names_long = char(M_.endo_names_long, 's3');
M_.endo_names = char(M_.endo_names, 's4');
M_.endo_names_tex = char(M_.endo_names_tex, 's4');
M_.endo_names_long = char(M_.endo_names_long, 's4');
M_.endo_names = char(M_.endo_names, 's5');
M_.endo_names_tex = char(M_.endo_names_tex, 's5');
M_.endo_names_long = char(M_.endo_names_long, 's5');
M_.endo_names = char(M_.endo_names, 's6');
M_.endo_names_tex = char(M_.endo_names_tex, 's6');
M_.endo_names_long = char(M_.endo_names_long, 's6');
M_.endo_names = char(M_.endo_names, 's7');
M_.endo_names_tex = char(M_.endo_names_tex, 's7');
M_.endo_names_long = char(M_.endo_names_long, 's7');
M_.endo_names = char(M_.endo_names, 's8');
M_.endo_names_tex = char(M_.endo_names_tex, 's8');
M_.endo_names_long = char(M_.endo_names_long, 's8');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_214');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_214');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_214');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_218');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_218');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_218');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_222');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_222');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_222');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_226');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_226');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_226');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_230');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_230');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_230');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_234');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_234');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_234');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_198');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_198');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_198');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_244');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_244');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_244');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_248');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_248');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_248');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_252');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_252');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_252');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_256');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_256');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_256');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_260');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_260');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_260');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_264');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_264');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_264');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_204');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_204');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_204');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_272');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_272');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_272');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_276');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_276');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_276');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_280');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_280');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_280');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_284');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_284');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_284');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_288');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_288');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_288');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_292');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_292');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_292');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_205');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_205');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_205');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LEAD_307');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LEAD\_307');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LEAD_307');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LEAD_311');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LEAD\_311');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LEAD_311');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LEAD_315');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LEAD\_315');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LEAD_315');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LEAD_319');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LEAD\_319');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LEAD_319');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LEAD_323');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LEAD\_323');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LEAD_323');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LEAD_327');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LEAD\_327');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LEAD_327');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LEAD_331');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LEAD\_331');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LEAD_331');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LEAD_211');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LEAD\_211');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LEAD_211');
M_.param_names = 'sigma';
M_.param_names_tex = 'sigma';
M_.param_names_long = 'sigma';
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'psi');
M_.param_names_tex = char(M_.param_names_tex, 'psi');
M_.param_names_long = char(M_.param_names_long, 'psi');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'phipi');
M_.param_names_tex = char(M_.param_names_tex, 'phipi');
M_.param_names_long = char(M_.param_names_long, 'phipi');
M_.param_names = char(M_.param_names, 'phiy');
M_.param_names_tex = char(M_.param_names_tex, 'phiy');
M_.param_names_long = char(M_.param_names_long, 'phiy');
M_.param_names = char(M_.param_names, 'etag');
M_.param_names_tex = char(M_.param_names_tex, 'etag');
M_.param_names_long = char(M_.param_names_long, 'etag');
M_.param_names = char(M_.param_names, 'etax');
M_.param_names_tex = char(M_.param_names_tex, 'etax');
M_.param_names_long = char(M_.param_names_long, 'etax');
M_.param_names = char(M_.param_names, 'rhog');
M_.param_names_tex = char(M_.param_names_tex, 'rhog');
M_.param_names_long = char(M_.param_names_long, 'rhog');
M_.param_names = char(M_.param_names, 'rhox');
M_.param_names_tex = char(M_.param_names_tex, 'rhox');
M_.param_names_long = char(M_.param_names_long, 'rhox');
M_.param_names = char(M_.param_names, 'rhoa');
M_.param_names_tex = char(M_.param_names_tex, 'rhoa');
M_.param_names_long = char(M_.param_names_long, 'rhoa');
M_.param_names = char(M_.param_names, 'rhoi');
M_.param_names_tex = char(M_.param_names_tex, 'rhoi');
M_.param_names_long = char(M_.param_names_long, 'rhoi');
M_.param_names = char(M_.param_names, 'sigmaa');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaa');
M_.param_names_long = char(M_.param_names_long, 'sigmaa');
M_.param_names = char(M_.param_names, 'sigmai');
M_.param_names_tex = char(M_.param_names_tex, 'sigmai');
M_.param_names_long = char(M_.param_names_long, 'sigmai');
M_.param_names = char(M_.param_names, 'sigmax');
M_.param_names_tex = char(M_.param_names_tex, 'sigmax');
M_.param_names_long = char(M_.param_names_long, 'sigmax');
M_.param_names = char(M_.param_names, 'sigmag');
M_.param_names_tex = char(M_.param_names_tex, 'sigmag');
M_.param_names_long = char(M_.param_names_long, 'sigmag');
M_.param_names = char(M_.param_names, 'cs');
M_.param_names_tex = char(M_.param_names_tex, 'cs');
M_.param_names_long = char(M_.param_names_long, 'cs');
M_.param_names = char(M_.param_names, 'is');
M_.param_names_tex = char(M_.param_names_tex, 'is');
M_.param_names_long = char(M_.param_names_long, 'is');
M_.param_names = char(M_.param_names, 'pis');
M_.param_names_tex = char(M_.param_names_tex, 'pis');
M_.param_names_long = char(M_.param_names_long, 'pis');
M_.param_names = char(M_.param_names, 'ns');
M_.param_names_tex = char(M_.param_names_tex, 'ns');
M_.param_names_long = char(M_.param_names_long, 'ns');
M_.param_names = char(M_.param_names, 'ws');
M_.param_names_tex = char(M_.param_names_tex, 'ws');
M_.param_names_long = char(M_.param_names_long, 'ws');
M_.param_names = char(M_.param_names, 'mcs');
M_.param_names_tex = char(M_.param_names_tex, 'mcs');
M_.param_names_long = char(M_.param_names_long, 'mcs');
M_.param_names = char(M_.param_names, 'as');
M_.param_names_tex = char(M_.param_names_tex, 'as');
M_.param_names_long = char(M_.param_names_long, 'as');
M_.param_names = char(M_.param_names, 'ys');
M_.param_names_tex = char(M_.param_names_tex, 'ys');
M_.param_names_long = char(M_.param_names_long, 'ys');
M_.param_names = char(M_.param_names, 'yfs');
M_.param_names_tex = char(M_.param_names_tex, 'yfs');
M_.param_names_long = char(M_.param_names_long, 'yfs');
M_.param_names = char(M_.param_names, 'vps');
M_.param_names_tex = char(M_.param_names_tex, 'vps');
M_.param_names_long = char(M_.param_names_long, 'vps');
M_.param_names = char(M_.param_names, 'pisharps');
M_.param_names_tex = char(M_.param_names_tex, 'pisharps');
M_.param_names_long = char(M_.param_names_long, 'pisharps');
M_.param_names = char(M_.param_names, 'x1s');
M_.param_names_tex = char(M_.param_names_tex, 'x1s');
M_.param_names_long = char(M_.param_names_long, 'x1s');
M_.param_names = char(M_.param_names, 'x2s');
M_.param_names_tex = char(M_.param_names_tex, 'x2s');
M_.param_names_long = char(M_.param_names_long, 'x2s');
M_.param_names = char(M_.param_names, 'gs');
M_.param_names_tex = char(M_.param_names_tex, 'gs');
M_.param_names_long = char(M_.param_names_long, 'gs');
M_.param_names = char(M_.param_names, 'nexs');
M_.param_names_tex = char(M_.param_names_tex, 'nexs');
M_.param_names_long = char(M_.param_names_long, 'nexs');
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 53;
M_.param_nbr = 33;
M_.orig_endo_nbr = 24;
M_.aux_vars(1).endo_index = 25;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 26;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 27;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 28;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 29;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 30;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 31;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 32;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 33;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 34;
M_.aux_vars(10).type = 0;
M_.aux_vars(11).endo_index = 35;
M_.aux_vars(11).type = 0;
M_.aux_vars(12).endo_index = 36;
M_.aux_vars(12).type = 0;
M_.aux_vars(13).endo_index = 37;
M_.aux_vars(13).type = 0;
M_.aux_vars(14).endo_index = 38;
M_.aux_vars(14).type = 0;
M_.aux_vars(15).endo_index = 39;
M_.aux_vars(15).type = 0;
M_.aux_vars(16).endo_index = 40;
M_.aux_vars(16).type = 0;
M_.aux_vars(17).endo_index = 41;
M_.aux_vars(17).type = 0;
M_.aux_vars(18).endo_index = 42;
M_.aux_vars(18).type = 0;
M_.aux_vars(19).endo_index = 43;
M_.aux_vars(19).type = 0;
M_.aux_vars(20).endo_index = 44;
M_.aux_vars(20).type = 0;
M_.aux_vars(21).endo_index = 45;
M_.aux_vars(21).type = 0;
M_.aux_vars(22).endo_index = 46;
M_.aux_vars(22).type = 2;
M_.aux_vars(23).endo_index = 47;
M_.aux_vars(23).type = 2;
M_.aux_vars(24).endo_index = 48;
M_.aux_vars(24).type = 2;
M_.aux_vars(25).endo_index = 49;
M_.aux_vars(25).type = 2;
M_.aux_vars(26).endo_index = 50;
M_.aux_vars(26).type = 2;
M_.aux_vars(27).endo_index = 51;
M_.aux_vars(27).type = 2;
M_.aux_vars(28).endo_index = 52;
M_.aux_vars(28).type = 2;
M_.aux_vars(29).endo_index = 53;
M_.aux_vars(29).type = 2;
M_.Sigma_e = zeros(4, 4);
M_.Correlation_matrix = eye(4, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('ZLB_eight_static');
erase_compiled_function('ZLB_eight_dynamic');
M_.lead_lag_incidence = [
 0 13 66;
 0 14 0;
 0 15 67;
 0 16 0;
 0 17 0;
 0 18 0;
 0 19 0;
 1 20 0;
 0 21 68;
 2 22 0;
 0 23 69;
 0 24 0;
 0 25 70;
 0 26 71;
 3 27 0;
 4 28 0;
 5 29 0;
 6 30 0;
 7 31 0;
 8 32 0;
 9 33 0;
 10 34 0;
 11 35 0;
 12 36 0;
 0 37 72;
 0 38 73;
 0 39 74;
 0 40 75;
 0 41 76;
 0 42 77;
 0 43 78;
 0 44 79;
 0 45 80;
 0 46 81;
 0 47 82;
 0 48 83;
 0 49 84;
 0 50 85;
 0 51 86;
 0 52 87;
 0 53 88;
 0 54 89;
 0 55 90;
 0 56 91;
 0 57 92;
 0 58 93;
 0 59 94;
 0 60 95;
 0 61 96;
 0 62 97;
 0 63 98;
 0 64 99;
 0 65 100;]';
M_.nstatic = 6;
M_.nfwrd   = 35;
M_.npred   = 12;
M_.nboth   = 0;
M_.nsfwrd   = 35;
M_.nspred   = 12;
M_.ndynamic   = 47;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:4];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(53, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = NaN(33, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 133;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
M_.params( 2 ) = .99;
beta = M_.params( 2 );
M_.params( 1 ) = 1;
sigma = M_.params( 1 );
M_.params( 4 ) = 1;
eta = M_.params( 4 );
M_.params( 3 ) = 1;
psi = M_.params( 3 );
M_.params( 6 ) = 10;
epsilon = M_.params( 6 );
M_.params( 7 ) = 1.5;
phipi = M_.params( 7 );
M_.params( 8 ) = 0;
phiy = M_.params( 8 );
M_.params( 9 ) = .1413;
etag = M_.params( 9 );
M_.params( 10 ) = .0320;
etax = M_.params( 10 );
M_.params( 13 ) = .95;
rhoa = M_.params( 13 );
M_.params( 14 ) = .0;
rhoi = M_.params( 14 );
M_.params( 11 ) = .9658;
rhog = M_.params( 11 );
M_.params( 12 ) = .8257;
rhox = M_.params( 12 );
M_.params( 15 ) = .1;
sigmaa = M_.params( 15 );
M_.params( 16 ) = .1;
sigmai = M_.params( 16 );
M_.params( 17 ) = .5010;
sigmax = M_.params( 17 );
M_.params( 18 ) = .1459;
sigmag = M_.params( 18 );
M_.params( 5 ) = .75;
phi = M_.params( 5 );
M_.params( 21 ) = 1;
pis = M_.params( 21 );
M_.params( 20 ) = 1/M_.params(2)*M_.params(21);
is = M_.params( 20 );
M_.params( 25 ) = 1;
as = M_.params( 25 );
M_.params( 29 ) = ((M_.params(21)^(1-M_.params(6))-M_.params(5))/(1-M_.params(5)))^(1/(1-M_.params(6)));
pisharps = M_.params( 29 );
M_.params( 28 ) = (1-M_.params(5))*(M_.params(21)/M_.params(29))^M_.params(6)/(1-M_.params(5)*M_.params(21)^M_.params(6));
vps = M_.params( 28 );
M_.params( 24 ) = (M_.params(6)-1)*M_.params(29)*(1-M_.params(21)^M_.params(6)*M_.params(2)*M_.params(5))/(1-M_.params(2)*M_.params(5)*M_.params(21)^(M_.params(6)-1))/M_.params(21)/M_.params(6);
mcs = M_.params( 24 );
M_.params( 22 ) = (M_.params(28)^M_.params(1)*M_.params(24)/M_.params(3)/(1-M_.params(10)-M_.params(9))^M_.params(1))^(1/(M_.params(1)+M_.params(4)));
ns = M_.params( 22 );
M_.params( 26 ) = M_.params(25)*M_.params(22)/M_.params(28);
ys = M_.params( 26 );
M_.params( 27 ) = ((M_.params(6)-1)/M_.params(6)/M_.params(3)/(1-M_.params(9)-M_.params(10))^M_.params(1))^(1/(M_.params(1)+M_.params(4)))*M_.params(25)^((1+M_.params(4))/(M_.params(1)+M_.params(4)));
yfs = M_.params( 27 );
M_.params( 32 ) = M_.params(9)*M_.params(26);
gs = M_.params( 32 );
M_.params( 33 ) = M_.params(10)*M_.params(26);
nexs = M_.params( 33 );
M_.params( 19 ) = (1-M_.params(9)-M_.params(10))*M_.params(26);
cs = M_.params( 19 );
M_.params( 23 ) = M_.params(24)*M_.params(25);
ws = M_.params( 23 );
M_.params( 30 ) = M_.params(26)*M_.params(24)*M_.params(19)^(-M_.params(1))/(1-M_.params(21)^M_.params(6)*M_.params(2)*M_.params(5));
x1s = M_.params( 30 );
M_.params( 31 ) = M_.params(26)*M_.params(19)^(-M_.params(1))/(1-M_.params(2)*M_.params(5)*M_.params(21)^(M_.params(6)-1));
x2s = M_.params( 31 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 1 ) = log(M_.params(19));
oo_.steady_state( 2 ) = log(M_.params(20));
oo_.steady_state( 3 ) = log(M_.params(21));
oo_.steady_state( 5 ) = log(M_.params(22));
oo_.steady_state( 6 ) = log(M_.params(23));
oo_.steady_state( 7 ) = log(M_.params(24));
oo_.steady_state( 8 ) = log(M_.params(25));
oo_.steady_state( 9 ) = log(M_.params(26));
oo_.steady_state( 11 ) = log(M_.params(27));
oo_.steady_state( 10 ) = log(M_.params(28));
oo_.steady_state( 12 ) = log(M_.params(29));
oo_.steady_state( 13 ) = log(M_.params(30));
oo_.steady_state( 14 ) = log(M_.params(31));
oo_.steady_state( 15 ) = log(M_.params(32));
oo_.steady_state( 4 ) = log(M_.params(20)/M_.params(21));
oo_.steady_state( 16 ) = log(M_.params(33));
oo_.steady_state( 17 ) = log(M_.params(20));
oo_.steady_state( 18 ) = log(M_.params(20));
oo_.steady_state( 19 ) = log(M_.params(20));
oo_.steady_state( 20 ) = log(M_.params(20));
oo_.steady_state( 21 ) = log(M_.params(20));
oo_.steady_state( 22 ) = log(M_.params(20));
oo_.steady_state( 23 ) = log(M_.params(20));
oo_.steady_state( 24 ) = log(M_.params(20));
oo_.steady_state(25)=oo_.steady_state(3);
oo_.steady_state(26)=oo_.steady_state(25);
oo_.steady_state(27)=oo_.steady_state(26);
oo_.steady_state(28)=oo_.steady_state(27);
oo_.steady_state(29)=oo_.steady_state(28);
oo_.steady_state(30)=oo_.steady_state(29);
oo_.steady_state(31)=oo_.steady_state(30);
oo_.steady_state(32)=oo_.steady_state(9);
oo_.steady_state(33)=oo_.steady_state(32);
oo_.steady_state(34)=oo_.steady_state(33);
oo_.steady_state(35)=oo_.steady_state(34);
oo_.steady_state(36)=oo_.steady_state(35);
oo_.steady_state(37)=oo_.steady_state(36);
oo_.steady_state(38)=oo_.steady_state(37);
oo_.steady_state(39)=oo_.steady_state(11);
oo_.steady_state(40)=oo_.steady_state(39);
oo_.steady_state(41)=oo_.steady_state(40);
oo_.steady_state(42)=oo_.steady_state(41);
oo_.steady_state(43)=oo_.steady_state(42);
oo_.steady_state(44)=oo_.steady_state(43);
oo_.steady_state(45)=oo_.steady_state(44);
oo_.steady_state(46)=oo_.exo_steady_state(2);
oo_.steady_state(47)=oo_.steady_state(46);
oo_.steady_state(48)=oo_.steady_state(47);
oo_.steady_state(49)=oo_.steady_state(48);
oo_.steady_state(50)=oo_.steady_state(49);
oo_.steady_state(51)=oo_.steady_state(50);
oo_.steady_state(52)=oo_.steady_state(51);
oo_.steady_state(53)=oo_.steady_state(52);
if M_.exo_nbr > 0;
	oo_.exo_simul = [ones(M_.maximum_lag,1)*oo_.exo_steady_state'];
end;
if M_.exo_det_nbr > 0;
	oo_.exo_det_simul = [ones(M_.maximum_lag,1)*oo_.exo_det_steady_state'];
end;
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = M_.params(15)^2;
M_.Sigma_e(2, 2) = M_.params(16)^2;
M_.Sigma_e(3, 3) = M_.params(18)^2;
M_.Sigma_e(4, 4) = M_.params(17)^2;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.nograph = 1;
options_.order = 1;
var_list_=[];
var_list_ = 'i';
var_list_ = char(var_list_, 'pi');
var_list_ = char(var_list_, 'n');
var_list_ = char(var_list_, 'w');
var_list_ = char(var_list_, 'mc');
var_list_ = char(var_list_, 'y');
var_list_ = char(var_list_, 'r');
var_list_ = char(var_list_, 'g');
var_list_ = char(var_list_, 'c');
var_list_ = char(var_list_, 'nex');
var_list_ = char(var_list_, 'yf');
info = stoch_simul(var_list_);
save('ZLB_eight_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('ZLB_eight_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('ZLB_eight_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('ZLB_eight_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('ZLB_eight_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
