%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_
options_ = [];
M_.fname = 'US_SW07';
%
% Some global variables initialization
%
global_initialization;
diary off;
logname_ = 'US_SW07.log';
if exist(logname_, 'file')
    delete(logname_)
end
diary(logname_)
M_.exo_names = 'ea';
M_.exo_names_tex = 'ea';
M_.exo_names = char(M_.exo_names, 'eb');
M_.exo_names_tex = char(M_.exo_names_tex, 'eb');
M_.exo_names = char(M_.exo_names, 'eqs');
M_.exo_names_tex = char(M_.exo_names_tex, 'eqs');
M_.exo_names = char(M_.exo_names, 'em');
M_.exo_names_tex = char(M_.exo_names_tex, 'em');
M_.exo_names = char(M_.exo_names, 'epinf');
M_.exo_names_tex = char(M_.exo_names_tex, 'epinf');
M_.exo_names = char(M_.exo_names, 'ew');
M_.exo_names_tex = char(M_.exo_names_tex, 'ew');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.endo_names = 'labobs';
M_.endo_names_tex = 'labobs';
M_.endo_names = char(M_.endo_names, 'robs');
M_.endo_names_tex = char(M_.endo_names_tex, 'robs');
M_.endo_names = char(M_.endo_names, 'pinfobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinfobs');
M_.endo_names = char(M_.endo_names, 'dy');
M_.endo_names_tex = char(M_.endo_names_tex, 'dy');
M_.endo_names = char(M_.endo_names, 'dc');
M_.endo_names_tex = char(M_.endo_names_tex, 'dc');
M_.endo_names = char(M_.endo_names, 'dinve');
M_.endo_names_tex = char(M_.endo_names_tex, 'dinve');
M_.endo_names = char(M_.endo_names, 'dw');
M_.endo_names_tex = char(M_.endo_names_tex, 'dw');
M_.endo_names = char(M_.endo_names, 'ewma');
M_.endo_names_tex = char(M_.endo_names_tex, 'ewma');
M_.endo_names = char(M_.endo_names, 'epinfma');
M_.endo_names_tex = char(M_.endo_names_tex, 'epinfma');
M_.endo_names = char(M_.endo_names, 'zcapf');
M_.endo_names_tex = char(M_.endo_names_tex, 'zcapf');
M_.endo_names = char(M_.endo_names, 'rkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkf');
M_.endo_names = char(M_.endo_names, 'kf');
M_.endo_names_tex = char(M_.endo_names_tex, 'kf');
M_.endo_names = char(M_.endo_names, 'pkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pkf');
M_.endo_names = char(M_.endo_names, 'cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cf');
M_.endo_names = char(M_.endo_names, 'invef');
M_.endo_names_tex = char(M_.endo_names_tex, 'invef');
M_.endo_names = char(M_.endo_names, 'yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'yf');
M_.endo_names = char(M_.endo_names, 'labf');
M_.endo_names_tex = char(M_.endo_names_tex, 'labf');
M_.endo_names = char(M_.endo_names, 'wf');
M_.endo_names_tex = char(M_.endo_names_tex, 'wf');
M_.endo_names = char(M_.endo_names, 'rrf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rrf');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names = char(M_.endo_names, 'zcap');
M_.endo_names_tex = char(M_.endo_names_tex, 'zcap');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names = char(M_.endo_names, 'pk');
M_.endo_names_tex = char(M_.endo_names_tex, 'pk');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names = char(M_.endo_names, 'inve');
M_.endo_names_tex = char(M_.endo_names_tex, 'inve');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names = char(M_.endo_names, 'lab');
M_.endo_names_tex = char(M_.endo_names_tex, 'lab');
M_.endo_names = char(M_.endo_names, 'pinf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinf');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names = char(M_.endo_names, 'qs');
M_.endo_names_tex = char(M_.endo_names_tex, 'qs');
M_.endo_names = char(M_.endo_names, 'ms');
M_.endo_names_tex = char(M_.endo_names_tex, 'ms');
M_.endo_names = char(M_.endo_names, 'spinf');
M_.endo_names_tex = char(M_.endo_names_tex, 'spinf');
M_.endo_names = char(M_.endo_names, 'sw');
M_.endo_names_tex = char(M_.endo_names_tex, 'sw');
M_.endo_names = char(M_.endo_names, 'kpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'kpf');
M_.endo_names = char(M_.endo_names, 'kp');
M_.endo_names_tex = char(M_.endo_names_tex, 'kp');
M_.endo_names = char(M_.endo_names, 'pinf4');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinf4');
M_.endo_names = char(M_.endo_names, 'eg');
M_.endo_names_tex = char(M_.endo_names_tex, 'eg');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_73');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_73');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_77');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_77');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_81');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_81');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_108');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_108');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_112');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_112');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_116');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_116');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_45_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_45\_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_45_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_45\_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_45_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_45\_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_42_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_42\_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_42_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_42\_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_42_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_42\_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_44_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_44\_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_44_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_44\_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_44_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_44\_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_28_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_28\_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_28_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_28\_2');
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names = char(M_.param_names, 'curvw');
M_.param_names_tex = char(M_.param_names_tex, 'curvw');
M_.param_names = char(M_.param_names, 'cgy');
M_.param_names_tex = char(M_.param_names_tex, 'cgy');
M_.param_names = char(M_.param_names, 'curvp');
M_.param_names_tex = char(M_.param_names_tex, 'curvp');
M_.param_names = char(M_.param_names, 'constelab');
M_.param_names_tex = char(M_.param_names_tex, 'constelab');
M_.param_names = char(M_.param_names, 'constepinf');
M_.param_names_tex = char(M_.param_names_tex, 'constepinf');
M_.param_names = char(M_.param_names, 'constebeta');
M_.param_names_tex = char(M_.param_names_tex, 'constebeta');
M_.param_names = char(M_.param_names, 'cmaw');
M_.param_names_tex = char(M_.param_names_tex, 'cmaw');
M_.param_names = char(M_.param_names, 'cmap');
M_.param_names_tex = char(M_.param_names_tex, 'cmap');
M_.param_names = char(M_.param_names, 'calfa');
M_.param_names_tex = char(M_.param_names_tex, 'calfa');
M_.param_names = char(M_.param_names, 'czcap');
M_.param_names_tex = char(M_.param_names_tex, 'czcap');
M_.param_names = char(M_.param_names, 'cbeta');
M_.param_names_tex = char(M_.param_names_tex, 'cbeta');
M_.param_names = char(M_.param_names, 'csadjcost');
M_.param_names_tex = char(M_.param_names_tex, 'csadjcost');
M_.param_names = char(M_.param_names, 'ctou');
M_.param_names_tex = char(M_.param_names_tex, 'ctou');
M_.param_names = char(M_.param_names, 'csigma');
M_.param_names_tex = char(M_.param_names_tex, 'csigma');
M_.param_names = char(M_.param_names, 'chabb');
M_.param_names_tex = char(M_.param_names_tex, 'chabb');
M_.param_names = char(M_.param_names, 'ccs');
M_.param_names_tex = char(M_.param_names_tex, 'ccs');
M_.param_names = char(M_.param_names, 'cinvs');
M_.param_names_tex = char(M_.param_names_tex, 'cinvs');
M_.param_names = char(M_.param_names, 'cfc');
M_.param_names_tex = char(M_.param_names_tex, 'cfc');
M_.param_names = char(M_.param_names, 'cindw');
M_.param_names_tex = char(M_.param_names_tex, 'cindw');
M_.param_names = char(M_.param_names, 'cprobw');
M_.param_names_tex = char(M_.param_names_tex, 'cprobw');
M_.param_names = char(M_.param_names, 'cindp');
M_.param_names_tex = char(M_.param_names_tex, 'cindp');
M_.param_names = char(M_.param_names, 'cprobp');
M_.param_names_tex = char(M_.param_names_tex, 'cprobp');
M_.param_names = char(M_.param_names, 'csigl');
M_.param_names_tex = char(M_.param_names_tex, 'csigl');
M_.param_names = char(M_.param_names, 'clandaw');
M_.param_names_tex = char(M_.param_names_tex, 'clandaw');
M_.param_names = char(M_.param_names, 'crdpi');
M_.param_names_tex = char(M_.param_names_tex, 'crdpi');
M_.param_names = char(M_.param_names, 'crpi');
M_.param_names_tex = char(M_.param_names_tex, 'crpi');
M_.param_names = char(M_.param_names, 'crdy');
M_.param_names_tex = char(M_.param_names_tex, 'crdy');
M_.param_names = char(M_.param_names, 'cry');
M_.param_names_tex = char(M_.param_names_tex, 'cry');
M_.param_names = char(M_.param_names, 'crr');
M_.param_names_tex = char(M_.param_names_tex, 'crr');
M_.param_names = char(M_.param_names, 'crhoa');
M_.param_names_tex = char(M_.param_names_tex, 'crhoa');
M_.param_names = char(M_.param_names, 'crhob');
M_.param_names_tex = char(M_.param_names_tex, 'crhob');
M_.param_names = char(M_.param_names, 'crhog');
M_.param_names_tex = char(M_.param_names_tex, 'crhog');
M_.param_names = char(M_.param_names, 'crhoqs');
M_.param_names_tex = char(M_.param_names_tex, 'crhoqs');
M_.param_names = char(M_.param_names, 'crhoms');
M_.param_names_tex = char(M_.param_names_tex, 'crhoms');
M_.param_names = char(M_.param_names, 'crhopinf');
M_.param_names_tex = char(M_.param_names_tex, 'crhopinf');
M_.param_names = char(M_.param_names, 'crhow');
M_.param_names_tex = char(M_.param_names_tex, 'crhow');
M_.param_names = char(M_.param_names, 'ctrend');
M_.param_names_tex = char(M_.param_names_tex, 'ctrend');
M_.param_names = char(M_.param_names, 'cg');
M_.param_names_tex = char(M_.param_names_tex, 'cg');
M_.param_names = char(M_.param_names, 'cgamma');
M_.param_names_tex = char(M_.param_names_tex, 'cgamma');
M_.param_names = char(M_.param_names, 'clandap');
M_.param_names_tex = char(M_.param_names_tex, 'clandap');
M_.param_names = char(M_.param_names, 'cbetabar');
M_.param_names_tex = char(M_.param_names_tex, 'cbetabar');
M_.param_names = char(M_.param_names, 'cr');
M_.param_names_tex = char(M_.param_names_tex, 'cr');
M_.param_names = char(M_.param_names, 'cpie');
M_.param_names_tex = char(M_.param_names_tex, 'cpie');
M_.param_names = char(M_.param_names, 'crk');
M_.param_names_tex = char(M_.param_names_tex, 'crk');
M_.param_names = char(M_.param_names, 'cw');
M_.param_names_tex = char(M_.param_names_tex, 'cw');
M_.param_names = char(M_.param_names, 'cikbar');
M_.param_names_tex = char(M_.param_names_tex, 'cikbar');
M_.param_names = char(M_.param_names, 'cik');
M_.param_names_tex = char(M_.param_names_tex, 'cik');
M_.param_names = char(M_.param_names, 'clk');
M_.param_names_tex = char(M_.param_names_tex, 'clk');
M_.param_names = char(M_.param_names, 'cky');
M_.param_names_tex = char(M_.param_names_tex, 'cky');
M_.param_names = char(M_.param_names, 'ciy');
M_.param_names_tex = char(M_.param_names_tex, 'ciy');
M_.param_names = char(M_.param_names, 'ccy');
M_.param_names_tex = char(M_.param_names_tex, 'ccy');
M_.param_names = char(M_.param_names, 'crkky');
M_.param_names_tex = char(M_.param_names_tex, 'crkky');
M_.param_names = char(M_.param_names, 'cwhlc');
M_.param_names_tex = char(M_.param_names_tex, 'cwhlc');
M_.param_names = char(M_.param_names, 'cwly');
M_.param_names_tex = char(M_.param_names_tex, 'cwly');
M_.param_names = char(M_.param_names, 'conster');
M_.param_names_tex = char(M_.param_names_tex, 'conster');
M_.exo_det_nbr = 0;
M_.exo_nbr = 8;
M_.endo_nbr = 65;
M_.param_nbr = 80;
M_.orig_endo_nbr = 48;
M_.aux_vars(1).endo_index = 49;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 50;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 51;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 52;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 53;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 54;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 55;
M_.aux_vars(7).type = 1;
M_.aux_vars(7).orig_index = 46;
M_.aux_vars(7).orig_lead_lag = -1;
M_.aux_vars(8).endo_index = 56;
M_.aux_vars(8).type = 1;
M_.aux_vars(8).orig_index = 46;
M_.aux_vars(8).orig_lead_lag = -2;
M_.aux_vars(9).endo_index = 57;
M_.aux_vars(9).type = 1;
M_.aux_vars(9).orig_index = 46;
M_.aux_vars(9).orig_lead_lag = -3;
M_.aux_vars(10).endo_index = 58;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 43;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 59;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 43;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 60;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 43;
M_.aux_vars(12).orig_lead_lag = -3;
M_.aux_vars(13).endo_index = 61;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 45;
M_.aux_vars(13).orig_lead_lag = -1;
M_.aux_vars(14).endo_index = 62;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 45;
M_.aux_vars(14).orig_lead_lag = -2;
M_.aux_vars(15).endo_index = 63;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 45;
M_.aux_vars(15).orig_lead_lag = -3;
M_.aux_vars(16).endo_index = 64;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 29;
M_.aux_vars(16).orig_lead_lag = -1;
M_.aux_vars(17).endo_index = 65;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 29;
M_.aux_vars(17).orig_lead_lag = -2;
M_.Sigma_e = zeros(8, 8);
M_.H = 0;
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('US_SW07_dynamic');
M_.lead_lag_incidence = [
 0 33 0;
 0 34 0;
 0 35 0;
 0 36 0;
 0 37 0;
 0 38 0;
 0 39 0;
 1 40 0;
 2 41 0;
 0 42 0;
 0 43 98;
 0 44 0;
 0 45 99;
 3 46 100;
 4 47 101;
 0 48 0;
 0 49 102;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 0;
 0 54 103;
 0 55 0;
 0 56 104;
 5 57 105;
 6 58 106;
 7 59 0;
 0 60 107;
 8 61 108;
 9 62 109;
 0 63 0;
 10 64 0;
 11 65 0;
 12 66 0;
 13 67 0;
 14 68 0;
 15 69 0;
 16 70 0;
 17 71 0;
 18 72 0;
 0 73 0;
 0 74 0;
 19 75 0;
 0 76 0;
 20 77 110;
 21 78 111;
 0 79 0;
 0 80 0;
 0 81 112;
 0 82 113;
 0 83 114;
 0 84 115;
 0 85 116;
 0 86 117;
 22 87 0;
 23 88 0;
 24 89 0;
 25 90 0;
 26 91 0;
 27 92 0;
 28 93 0;
 29 94 0;
 30 95 0;
 31 96 0;
 32 97 0;]';
M_.equations_tags = {
};
M_.exo_names_orig_ord = [1:8];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(65, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(8, 1);
M_.params = repmat(NaN,80, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 230;
M_.NNZDerivatives(2) = 0;
M_.NNZDerivatives(3) = -1;
M_.params( 38 ) = .025;
ctou = M_.params( 38 );
M_.params( 49 ) = 1.5;
clandaw = M_.params( 49 );
M_.params( 63 ) = 0.18;
cg = M_.params( 63 );
M_.params( 28 ) = 10;
curvp = M_.params( 28 );
M_.params( 26 ) = 10;
curvw = M_.params( 26 );
M_.params( 62 ) = 0.4312;
ctrend = M_.params( 62 );
M_.params( 64 ) = 1+M_.params(62)/100;
cgamma = M_.params( 64 );
M_.params( 31 ) = 0.1657;
constebeta = M_.params( 31 );
M_.params( 36 ) = 100/(100+M_.params(31));
cbeta = M_.params( 36 );
M_.params( 30 ) = 0.7869;
constepinf = M_.params( 30 );
M_.params( 68 ) = 1+M_.params(30)/100;
cpie = M_.params( 68 );
M_.params( 29 ) = 0.5509;
constelab = M_.params( 29 );
M_.params( 34 ) = 0.1901;
calfa = M_.params( 34 );
M_.params( 39 ) = 1.3808;
csigma = M_.params( 39 );
M_.params( 43 ) = 1.6064;
cfc = M_.params( 43 );
M_.params( 27 ) = 0.5187;
cgy = M_.params( 27 );
M_.params( 37 ) = 5.7606;
csadjcost = M_.params( 37 );
M_.params( 40 ) = 0.7133;
chabb = M_.params( 40 );
M_.params( 45 ) = 0.7061;
cprobw = M_.params( 45 );
M_.params( 48 ) = 1.8383;
csigl = M_.params( 48 );
M_.params( 47 ) = 0.6523;
cprobp = M_.params( 47 );
M_.params( 44 ) = 0.5845;
cindw = M_.params( 44 );
M_.params( 46 ) = 0.2432;
cindp = M_.params( 46 );
M_.params( 35 ) = 0.5462;
czcap = M_.params( 35 );
M_.params( 51 ) = 2.0443;
crpi = M_.params( 51 );
M_.params( 54 ) = 0.8103;
crr = M_.params( 54 );
M_.params( 53 ) = 0.0882;
cry = M_.params( 53 );
M_.params( 52 ) = 0.2247;
crdy = M_.params( 52 );
M_.params( 55 ) = 0.9577;
crhoa = M_.params( 55 );
M_.params( 56 ) = 0.2194;
crhob = M_.params( 56 );
M_.params( 57 ) = 0.9767;
crhog = M_.params( 57 );
M_.params( 58 ) = 0.7113;
crhoqs = M_.params( 58 );
M_.params( 59 ) = 0.1479;
crhoms = M_.params( 59 );
M_.params( 60 ) = 0.8895;
crhopinf = M_.params( 60 );
M_.params( 61 ) = 0.9688;
crhow = M_.params( 61 );
M_.params( 33 ) = 0.7010;
cmap = M_.params( 33 );
M_.params( 32 ) = 0.8503;
cmaw = M_.params( 32 );
M_.params( 65 ) = M_.params(43);
clandap = M_.params( 65 );
M_.params( 66 ) = M_.params(36)*M_.params(64)^(-M_.params(39));
cbetabar = M_.params( 66 );
M_.params( 67 ) = M_.params(68)/(M_.params(36)*M_.params(64)^(-M_.params(39)));
cr = M_.params( 67 );
M_.params( 69 ) = M_.params(36)^(-1)*M_.params(64)^M_.params(39)-(1-M_.params(38));
crk = M_.params( 69 );
M_.params( 70 ) = (M_.params(34)^M_.params(34)*(1-M_.params(34))^(1-M_.params(34))/(M_.params(65)*M_.params(69)^M_.params(34)))^(1/(1-M_.params(34)));
cw = M_.params( 70 );
M_.params( 71 ) = 1-(1-M_.params(38))/M_.params(64);
cikbar = M_.params( 71 );
M_.params( 72 ) = M_.params(64)*(1-(1-M_.params(38))/M_.params(64));
cik = M_.params( 72 );
M_.params( 73 ) = (1-M_.params(34))/M_.params(34)*M_.params(69)/M_.params(70);
clk = M_.params( 73 );
M_.params( 74 ) = M_.params(43)*M_.params(73)^(M_.params(34)-1);
cky = M_.params( 74 );
M_.params( 75 ) = M_.params(72)*M_.params(74);
ciy = M_.params( 75 );
M_.params( 76 ) = 1-M_.params(63)-M_.params(72)*M_.params(74);
ccy = M_.params( 76 );
M_.params( 77 ) = M_.params(69)*M_.params(74);
crkky = M_.params( 77 );
M_.params( 78 ) = M_.params(74)*M_.params(69)*(1-M_.params(34))*1/M_.params(49)/M_.params(34)/M_.params(76);
cwhlc = M_.params( 78 );
M_.params( 79 ) = 1-M_.params(69)*M_.params(74);
cwly = M_.params( 79 );
M_.params( 80 ) = 100*(M_.params(67)-1);
conster = M_.params( 80 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:24                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);                                                            
M_.params( 25 ) = 1;
coffispol = M_.params( 25 );
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.4582)^2;
M_.Sigma_e(2, 2) = (0.2400)^2;
M_.Sigma_e(3, 3) = (0.4526)^2;
M_.Sigma_e(4, 4) = (0.2449)^2;
M_.Sigma_e(5, 5) = (0.1410)^2;
M_.Sigma_e(6, 6) = (0.2446)^2;
M_.Sigma_e(8, 8) = (0.5291)^2;
M_.sigma_e_is_diagonal = 1;
save('US_SW07_results.mat', 'oo_', 'M_', 'options_');
diary off

disp(['Total computing time : ' dynsec2hms(toc) ]);
